from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.attachment_ref_mvo import AttachmentRefMVO
from openapi_server.models.characteristic_mvo import CharacteristicMVO
from openapi_server.models.external_identifier_mvo import ExternalIdentifierMVO
from openapi_server.models.feature_mvo import FeatureMVO
from openapi_server.models.intent_ref_mvo import IntentRefMVO
from openapi_server.models.note_mvo import NoteMVO
from openapi_server.models.related_party_ref_or_party_role_ref_mvo import RelatedPartyRefOrPartyRoleRefMVO
from openapi_server.models.related_place_ref_mvo import RelatedPlaceRefMVO
from openapi_server.models.related_resource_order_item_mvo import RelatedResourceOrderItemMVO
from openapi_server.models.resource_administrative_state_type import ResourceAdministrativeStateType
from openapi_server.models.resource_mvo import ResourceMVO
from openapi_server.models.resource_operational_state_type import ResourceOperationalStateType
from openapi_server.models.resource_ref_or_value_mvo import ResourceRefOrValueMVO
from openapi_server.models.resource_relationship_mvo import ResourceRelationshipMVO
from openapi_server.models.resource_specification_ref_mvo import ResourceSpecificationRefMVO
from openapi_server.models.resource_status_type import ResourceStatusType
from openapi_server.models.resource_usage_state_type import ResourceUsageStateType
from openapi_server.models.time_period import TimePeriod
from openapi_server import util

from openapi_server.models.attachment_ref_mvo import AttachmentRefMVO  # noqa: E501
from openapi_server.models.characteristic_mvo import CharacteristicMVO  # noqa: E501
from openapi_server.models.external_identifier_mvo import ExternalIdentifierMVO  # noqa: E501
from openapi_server.models.feature_mvo import FeatureMVO  # noqa: E501
from openapi_server.models.intent_ref_mvo import IntentRefMVO  # noqa: E501
from openapi_server.models.note_mvo import NoteMVO  # noqa: E501
from openapi_server.models.related_party_ref_or_party_role_ref_mvo import RelatedPartyRefOrPartyRoleRefMVO  # noqa: E501
from openapi_server.models.related_place_ref_mvo import RelatedPlaceRefMVO  # noqa: E501
from openapi_server.models.related_resource_order_item_mvo import RelatedResourceOrderItemMVO  # noqa: E501
from openapi_server.models.resource_administrative_state_type import ResourceAdministrativeStateType  # noqa: E501
from openapi_server.models.resource_mvo import ResourceMVO  # noqa: E501
from openapi_server.models.resource_operational_state_type import ResourceOperationalStateType  # noqa: E501
from openapi_server.models.resource_ref_or_value_mvo import ResourceRefOrValueMVO  # noqa: E501
from openapi_server.models.resource_relationship_mvo import ResourceRelationshipMVO  # noqa: E501
from openapi_server.models.resource_specification_ref_mvo import ResourceSpecificationRefMVO  # noqa: E501
from openapi_server.models.resource_status_type import ResourceStatusType  # noqa: E501
from openapi_server.models.resource_usage_state_type import ResourceUsageStateType  # noqa: E501
from openapi_server.models.time_period import TimePeriod  # noqa: E501

class LogicalResourceMVO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, base_type=None, schema_location=None, href=None, id=None, category=None, description=None, name=None, end_operating_date=None, administrative_state=None, operational_state=None, resource_status=None, usage_state=None, valid_for=None, note=None, resource_order_item=None, place=None, related_party=None, supporting_resource=None, resource_relationship=None, resource_characteristic=None, attachment=None, resource_specification=None, start_operating_date=None, resource_version=None, activation_feature=None, intent=None, external_identifier=None, value=None):  # noqa: E501
        """LogicalResourceMVO - a model defined in OpenAPI

        :param type: The type of this LogicalResourceMVO.  # noqa: E501
        :type type: str
        :param base_type: The base_type of this LogicalResourceMVO.  # noqa: E501
        :type base_type: str
        :param schema_location: The schema_location of this LogicalResourceMVO.  # noqa: E501
        :type schema_location: str
        :param href: The href of this LogicalResourceMVO.  # noqa: E501
        :type href: str
        :param id: The id of this LogicalResourceMVO.  # noqa: E501
        :type id: str
        :param category: The category of this LogicalResourceMVO.  # noqa: E501
        :type category: str
        :param description: The description of this LogicalResourceMVO.  # noqa: E501
        :type description: str
        :param name: The name of this LogicalResourceMVO.  # noqa: E501
        :type name: str
        :param end_operating_date: The end_operating_date of this LogicalResourceMVO.  # noqa: E501
        :type end_operating_date: datetime
        :param administrative_state: The administrative_state of this LogicalResourceMVO.  # noqa: E501
        :type administrative_state: ResourceAdministrativeStateType
        :param operational_state: The operational_state of this LogicalResourceMVO.  # noqa: E501
        :type operational_state: ResourceOperationalStateType
        :param resource_status: The resource_status of this LogicalResourceMVO.  # noqa: E501
        :type resource_status: ResourceStatusType
        :param usage_state: The usage_state of this LogicalResourceMVO.  # noqa: E501
        :type usage_state: ResourceUsageStateType
        :param valid_for: The valid_for of this LogicalResourceMVO.  # noqa: E501
        :type valid_for: TimePeriod
        :param note: The note of this LogicalResourceMVO.  # noqa: E501
        :type note: List[NoteMVO]
        :param resource_order_item: The resource_order_item of this LogicalResourceMVO.  # noqa: E501
        :type resource_order_item: List[RelatedResourceOrderItemMVO]
        :param place: The place of this LogicalResourceMVO.  # noqa: E501
        :type place: List[RelatedPlaceRefMVO]
        :param related_party: The related_party of this LogicalResourceMVO.  # noqa: E501
        :type related_party: List[RelatedPartyRefOrPartyRoleRefMVO]
        :param supporting_resource: The supporting_resource of this LogicalResourceMVO.  # noqa: E501
        :type supporting_resource: List[ResourceRefOrValueMVO]
        :param resource_relationship: The resource_relationship of this LogicalResourceMVO.  # noqa: E501
        :type resource_relationship: List[ResourceRelationshipMVO]
        :param resource_characteristic: The resource_characteristic of this LogicalResourceMVO.  # noqa: E501
        :type resource_characteristic: List[CharacteristicMVO]
        :param attachment: The attachment of this LogicalResourceMVO.  # noqa: E501
        :type attachment: List[AttachmentRefMVO]
        :param resource_specification: The resource_specification of this LogicalResourceMVO.  # noqa: E501
        :type resource_specification: ResourceSpecificationRefMVO
        :param start_operating_date: The start_operating_date of this LogicalResourceMVO.  # noqa: E501
        :type start_operating_date: datetime
        :param resource_version: The resource_version of this LogicalResourceMVO.  # noqa: E501
        :type resource_version: str
        :param activation_feature: The activation_feature of this LogicalResourceMVO.  # noqa: E501
        :type activation_feature: List[FeatureMVO]
        :param intent: The intent of this LogicalResourceMVO.  # noqa: E501
        :type intent: IntentRefMVO
        :param external_identifier: The external_identifier of this LogicalResourceMVO.  # noqa: E501
        :type external_identifier: List[ExternalIdentifierMVO]
        :param value: The value of this LogicalResourceMVO.  # noqa: E501
        :type value: str
        """
        self.openapi_types = {
            'type': str,
            'base_type': str,
            'schema_location': str,
            'href': str,
            'id': str,
            'category': str,
            'description': str,
            'name': str,
            'end_operating_date': datetime,
            'administrative_state': ResourceAdministrativeStateType,
            'operational_state': ResourceOperationalStateType,
            'resource_status': ResourceStatusType,
            'usage_state': ResourceUsageStateType,
            'valid_for': TimePeriod,
            'note': List[NoteMVO],
            'resource_order_item': List[RelatedResourceOrderItemMVO],
            'place': List[RelatedPlaceRefMVO],
            'related_party': List[RelatedPartyRefOrPartyRoleRefMVO],
            'supporting_resource': List[ResourceRefOrValueMVO],
            'resource_relationship': List[ResourceRelationshipMVO],
            'resource_characteristic': List[CharacteristicMVO],
            'attachment': List[AttachmentRefMVO],
            'resource_specification': ResourceSpecificationRefMVO,
            'start_operating_date': datetime,
            'resource_version': str,
            'activation_feature': List[FeatureMVO],
            'intent': IntentRefMVO,
            'external_identifier': List[ExternalIdentifierMVO],
            'value': str
        }

        self.attribute_map = {
            'type': '@type',
            'base_type': '@baseType',
            'schema_location': '@schemaLocation',
            'href': 'href',
            'id': 'id',
            'category': 'category',
            'description': 'description',
            'name': 'name',
            'end_operating_date': 'endOperatingDate',
            'administrative_state': 'administrativeState',
            'operational_state': 'operationalState',
            'resource_status': 'resourceStatus',
            'usage_state': 'usageState',
            'valid_for': 'validFor',
            'note': 'note',
            'resource_order_item': 'resourceOrderItem',
            'place': 'place',
            'related_party': 'relatedParty',
            'supporting_resource': 'supportingResource',
            'resource_relationship': 'resourceRelationship',
            'resource_characteristic': 'resourceCharacteristic',
            'attachment': 'attachment',
            'resource_specification': 'resourceSpecification',
            'start_operating_date': 'startOperatingDate',
            'resource_version': 'resourceVersion',
            'activation_feature': 'activationFeature',
            'intent': 'intent',
            'external_identifier': 'externalIdentifier',
            'value': 'value'
        }

        self._type = type
        self._base_type = base_type
        self._schema_location = schema_location
        self._href = href
        self._id = id
        self._category = category
        self._description = description
        self._name = name
        self._end_operating_date = end_operating_date
        self._administrative_state = administrative_state
        self._operational_state = operational_state
        self._resource_status = resource_status
        self._usage_state = usage_state
        self._valid_for = valid_for
        self._note = note
        self._resource_order_item = resource_order_item
        self._place = place
        self._related_party = related_party
        self._supporting_resource = supporting_resource
        self._resource_relationship = resource_relationship
        self._resource_characteristic = resource_characteristic
        self._attachment = attachment
        self._resource_specification = resource_specification
        self._start_operating_date = start_operating_date
        self._resource_version = resource_version
        self._activation_feature = activation_feature
        self._intent = intent
        self._external_identifier = external_identifier
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'LogicalResourceMVO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LogicalResource_MVO of this LogicalResourceMVO.  # noqa: E501
        :rtype: LogicalResourceMVO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this LogicalResourceMVO.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :return: The type of this LogicalResourceMVO.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this LogicalResourceMVO.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :param type: The type of this LogicalResourceMVO.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def base_type(self) -> str:
        """Gets the base_type of this LogicalResourceMVO.

        When sub-classing, this defines the super-class  # noqa: E501

        :return: The base_type of this LogicalResourceMVO.
        :rtype: str
        """
        return self._base_type

    @base_type.setter
    def base_type(self, base_type: str):
        """Sets the base_type of this LogicalResourceMVO.

        When sub-classing, this defines the super-class  # noqa: E501

        :param base_type: The base_type of this LogicalResourceMVO.
        :type base_type: str
        """

        self._base_type = base_type

    @property
    def schema_location(self) -> str:
        """Gets the schema_location of this LogicalResourceMVO.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :return: The schema_location of this LogicalResourceMVO.
        :rtype: str
        """
        return self._schema_location

    @schema_location.setter
    def schema_location(self, schema_location: str):
        """Sets the schema_location of this LogicalResourceMVO.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :param schema_location: The schema_location of this LogicalResourceMVO.
        :type schema_location: str
        """

        self._schema_location = schema_location

    @property
    def href(self) -> str:
        """Gets the href of this LogicalResourceMVO.

        Hyperlink reference  # noqa: E501

        :return: The href of this LogicalResourceMVO.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this LogicalResourceMVO.

        Hyperlink reference  # noqa: E501

        :param href: The href of this LogicalResourceMVO.
        :type href: str
        """

        self._href = href

    @property
    def id(self) -> str:
        """Gets the id of this LogicalResourceMVO.

        unique identifier  # noqa: E501

        :return: The id of this LogicalResourceMVO.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this LogicalResourceMVO.

        unique identifier  # noqa: E501

        :param id: The id of this LogicalResourceMVO.
        :type id: str
        """

        self._id = id

    @property
    def category(self) -> str:
        """Gets the category of this LogicalResourceMVO.

        Category of the concrete resource. e.g Gold, Silver for MSISDN concrete resource  # noqa: E501

        :return: The category of this LogicalResourceMVO.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this LogicalResourceMVO.

        Category of the concrete resource. e.g Gold, Silver for MSISDN concrete resource  # noqa: E501

        :param category: The category of this LogicalResourceMVO.
        :type category: str
        """

        self._category = category

    @property
    def description(self) -> str:
        """Gets the description of this LogicalResourceMVO.

        free-text description of the resource  # noqa: E501

        :return: The description of this LogicalResourceMVO.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this LogicalResourceMVO.

        free-text description of the resource  # noqa: E501

        :param description: The description of this LogicalResourceMVO.
        :type description: str
        """

        self._description = description

    @property
    def name(self) -> str:
        """Gets the name of this LogicalResourceMVO.

        the name of the resource  # noqa: E501

        :return: The name of this LogicalResourceMVO.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this LogicalResourceMVO.

        the name of the resource  # noqa: E501

        :param name: The name of this LogicalResourceMVO.
        :type name: str
        """

        self._name = name

    @property
    def end_operating_date(self) -> datetime:
        """Gets the end_operating_date of this LogicalResourceMVO.

        A date time( DateTime). The date till the resource is operating  # noqa: E501

        :return: The end_operating_date of this LogicalResourceMVO.
        :rtype: datetime
        """
        return self._end_operating_date

    @end_operating_date.setter
    def end_operating_date(self, end_operating_date: datetime):
        """Sets the end_operating_date of this LogicalResourceMVO.

        A date time( DateTime). The date till the resource is operating  # noqa: E501

        :param end_operating_date: The end_operating_date of this LogicalResourceMVO.
        :type end_operating_date: datetime
        """

        self._end_operating_date = end_operating_date

    @property
    def administrative_state(self) -> ResourceAdministrativeStateType:
        """Gets the administrative_state of this LogicalResourceMVO.


        :return: The administrative_state of this LogicalResourceMVO.
        :rtype: ResourceAdministrativeStateType
        """
        return self._administrative_state

    @administrative_state.setter
    def administrative_state(self, administrative_state: ResourceAdministrativeStateType):
        """Sets the administrative_state of this LogicalResourceMVO.


        :param administrative_state: The administrative_state of this LogicalResourceMVO.
        :type administrative_state: ResourceAdministrativeStateType
        """

        self._administrative_state = administrative_state

    @property
    def operational_state(self) -> ResourceOperationalStateType:
        """Gets the operational_state of this LogicalResourceMVO.


        :return: The operational_state of this LogicalResourceMVO.
        :rtype: ResourceOperationalStateType
        """
        return self._operational_state

    @operational_state.setter
    def operational_state(self, operational_state: ResourceOperationalStateType):
        """Sets the operational_state of this LogicalResourceMVO.


        :param operational_state: The operational_state of this LogicalResourceMVO.
        :type operational_state: ResourceOperationalStateType
        """

        self._operational_state = operational_state

    @property
    def resource_status(self) -> ResourceStatusType:
        """Gets the resource_status of this LogicalResourceMVO.


        :return: The resource_status of this LogicalResourceMVO.
        :rtype: ResourceStatusType
        """
        return self._resource_status

    @resource_status.setter
    def resource_status(self, resource_status: ResourceStatusType):
        """Sets the resource_status of this LogicalResourceMVO.


        :param resource_status: The resource_status of this LogicalResourceMVO.
        :type resource_status: ResourceStatusType
        """

        self._resource_status = resource_status

    @property
    def usage_state(self) -> ResourceUsageStateType:
        """Gets the usage_state of this LogicalResourceMVO.


        :return: The usage_state of this LogicalResourceMVO.
        :rtype: ResourceUsageStateType
        """
        return self._usage_state

    @usage_state.setter
    def usage_state(self, usage_state: ResourceUsageStateType):
        """Sets the usage_state of this LogicalResourceMVO.


        :param usage_state: The usage_state of this LogicalResourceMVO.
        :type usage_state: ResourceUsageStateType
        """

        self._usage_state = usage_state

    @property
    def valid_for(self) -> TimePeriod:
        """Gets the valid_for of this LogicalResourceMVO.


        :return: The valid_for of this LogicalResourceMVO.
        :rtype: TimePeriod
        """
        return self._valid_for

    @valid_for.setter
    def valid_for(self, valid_for: TimePeriod):
        """Sets the valid_for of this LogicalResourceMVO.


        :param valid_for: The valid_for of this LogicalResourceMVO.
        :type valid_for: TimePeriod
        """

        self._valid_for = valid_for

    @property
    def note(self) -> List[NoteMVO]:
        """Gets the note of this LogicalResourceMVO.


        :return: The note of this LogicalResourceMVO.
        :rtype: List[NoteMVO]
        """
        return self._note

    @note.setter
    def note(self, note: List[NoteMVO]):
        """Sets the note of this LogicalResourceMVO.


        :param note: The note of this LogicalResourceMVO.
        :type note: List[NoteMVO]
        """

        self._note = note

    @property
    def resource_order_item(self) -> List[RelatedResourceOrderItemMVO]:
        """Gets the resource_order_item of this LogicalResourceMVO.

        A list of resource order items related to this resource  # noqa: E501

        :return: The resource_order_item of this LogicalResourceMVO.
        :rtype: List[RelatedResourceOrderItemMVO]
        """
        return self._resource_order_item

    @resource_order_item.setter
    def resource_order_item(self, resource_order_item: List[RelatedResourceOrderItemMVO]):
        """Sets the resource_order_item of this LogicalResourceMVO.

        A list of resource order items related to this resource  # noqa: E501

        :param resource_order_item: The resource_order_item of this LogicalResourceMVO.
        :type resource_order_item: List[RelatedResourceOrderItemMVO]
        """

        self._resource_order_item = resource_order_item

    @property
    def place(self) -> List[RelatedPlaceRefMVO]:
        """Gets the place of this LogicalResourceMVO.


        :return: The place of this LogicalResourceMVO.
        :rtype: List[RelatedPlaceRefMVO]
        """
        return self._place

    @place.setter
    def place(self, place: List[RelatedPlaceRefMVO]):
        """Sets the place of this LogicalResourceMVO.


        :param place: The place of this LogicalResourceMVO.
        :type place: List[RelatedPlaceRefMVO]
        """

        self._place = place

    @property
    def related_party(self) -> List[RelatedPartyRefOrPartyRoleRefMVO]:
        """Gets the related_party of this LogicalResourceMVO.


        :return: The related_party of this LogicalResourceMVO.
        :rtype: List[RelatedPartyRefOrPartyRoleRefMVO]
        """
        return self._related_party

    @related_party.setter
    def related_party(self, related_party: List[RelatedPartyRefOrPartyRoleRefMVO]):
        """Sets the related_party of this LogicalResourceMVO.


        :param related_party: The related_party of this LogicalResourceMVO.
        :type related_party: List[RelatedPartyRefOrPartyRoleRefMVO]
        """

        self._related_party = related_party

    @property
    def supporting_resource(self) -> List[ResourceRefOrValueMVO]:
        """Gets the supporting_resource of this LogicalResourceMVO.

        A list of supporting resources (SupportingResource [*]). A collection of resources that support this resource (bundling, link ResourceSpecification)  # noqa: E501

        :return: The supporting_resource of this LogicalResourceMVO.
        :rtype: List[ResourceRefOrValueMVO]
        """
        return self._supporting_resource

    @supporting_resource.setter
    def supporting_resource(self, supporting_resource: List[ResourceRefOrValueMVO]):
        """Sets the supporting_resource of this LogicalResourceMVO.

        A list of supporting resources (SupportingResource [*]). A collection of resources that support this resource (bundling, link ResourceSpecification)  # noqa: E501

        :param supporting_resource: The supporting_resource of this LogicalResourceMVO.
        :type supporting_resource: List[ResourceRefOrValueMVO]
        """

        self._supporting_resource = supporting_resource

    @property
    def resource_relationship(self) -> List[ResourceRelationshipMVO]:
        """Gets the resource_relationship of this LogicalResourceMVO.


        :return: The resource_relationship of this LogicalResourceMVO.
        :rtype: List[ResourceRelationshipMVO]
        """
        return self._resource_relationship

    @resource_relationship.setter
    def resource_relationship(self, resource_relationship: List[ResourceRelationshipMVO]):
        """Sets the resource_relationship of this LogicalResourceMVO.


        :param resource_relationship: The resource_relationship of this LogicalResourceMVO.
        :type resource_relationship: List[ResourceRelationshipMVO]
        """

        self._resource_relationship = resource_relationship

    @property
    def resource_characteristic(self) -> List[CharacteristicMVO]:
        """Gets the resource_characteristic of this LogicalResourceMVO.


        :return: The resource_characteristic of this LogicalResourceMVO.
        :rtype: List[CharacteristicMVO]
        """
        return self._resource_characteristic

    @resource_characteristic.setter
    def resource_characteristic(self, resource_characteristic: List[CharacteristicMVO]):
        """Sets the resource_characteristic of this LogicalResourceMVO.


        :param resource_characteristic: The resource_characteristic of this LogicalResourceMVO.
        :type resource_characteristic: List[CharacteristicMVO]
        """

        self._resource_characteristic = resource_characteristic

    @property
    def attachment(self) -> List[AttachmentRefMVO]:
        """Gets the attachment of this LogicalResourceMVO.


        :return: The attachment of this LogicalResourceMVO.
        :rtype: List[AttachmentRefMVO]
        """
        return self._attachment

    @attachment.setter
    def attachment(self, attachment: List[AttachmentRefMVO]):
        """Sets the attachment of this LogicalResourceMVO.


        :param attachment: The attachment of this LogicalResourceMVO.
        :type attachment: List[AttachmentRefMVO]
        """

        self._attachment = attachment

    @property
    def resource_specification(self) -> ResourceSpecificationRefMVO:
        """Gets the resource_specification of this LogicalResourceMVO.


        :return: The resource_specification of this LogicalResourceMVO.
        :rtype: ResourceSpecificationRefMVO
        """
        return self._resource_specification

    @resource_specification.setter
    def resource_specification(self, resource_specification: ResourceSpecificationRefMVO):
        """Sets the resource_specification of this LogicalResourceMVO.


        :param resource_specification: The resource_specification of this LogicalResourceMVO.
        :type resource_specification: ResourceSpecificationRefMVO
        """

        self._resource_specification = resource_specification

    @property
    def start_operating_date(self) -> datetime:
        """Gets the start_operating_date of this LogicalResourceMVO.

        A date time( DateTime). The date from which the resource is operating  # noqa: E501

        :return: The start_operating_date of this LogicalResourceMVO.
        :rtype: datetime
        """
        return self._start_operating_date

    @start_operating_date.setter
    def start_operating_date(self, start_operating_date: datetime):
        """Sets the start_operating_date of this LogicalResourceMVO.

        A date time( DateTime). The date from which the resource is operating  # noqa: E501

        :param start_operating_date: The start_operating_date of this LogicalResourceMVO.
        :type start_operating_date: datetime
        """

        self._start_operating_date = start_operating_date

    @property
    def resource_version(self) -> str:
        """Gets the resource_version of this LogicalResourceMVO.

        A field that identifies the specific version of an instance of a resource.  # noqa: E501

        :return: The resource_version of this LogicalResourceMVO.
        :rtype: str
        """
        return self._resource_version

    @resource_version.setter
    def resource_version(self, resource_version: str):
        """Sets the resource_version of this LogicalResourceMVO.

        A field that identifies the specific version of an instance of a resource.  # noqa: E501

        :param resource_version: The resource_version of this LogicalResourceMVO.
        :type resource_version: str
        """

        self._resource_version = resource_version

    @property
    def activation_feature(self) -> List[FeatureMVO]:
        """Gets the activation_feature of this LogicalResourceMVO.

        Configuration features  # noqa: E501

        :return: The activation_feature of this LogicalResourceMVO.
        :rtype: List[FeatureMVO]
        """
        return self._activation_feature

    @activation_feature.setter
    def activation_feature(self, activation_feature: List[FeatureMVO]):
        """Sets the activation_feature of this LogicalResourceMVO.

        Configuration features  # noqa: E501

        :param activation_feature: The activation_feature of this LogicalResourceMVO.
        :type activation_feature: List[FeatureMVO]
        """

        self._activation_feature = activation_feature

    @property
    def intent(self) -> IntentRefMVO:
        """Gets the intent of this LogicalResourceMVO.


        :return: The intent of this LogicalResourceMVO.
        :rtype: IntentRefMVO
        """
        return self._intent

    @intent.setter
    def intent(self, intent: IntentRefMVO):
        """Sets the intent of this LogicalResourceMVO.


        :param intent: The intent of this LogicalResourceMVO.
        :type intent: IntentRefMVO
        """

        self._intent = intent

    @property
    def external_identifier(self) -> List[ExternalIdentifierMVO]:
        """Gets the external_identifier of this LogicalResourceMVO.

        An identification of this resource that is owned by or originates in a software system different from the current system. The structure identifies the system itself, the nature of the resource within the system and the unique ID of the resource within the system. It is anticipated that multiple external IDs can be held for a single resource, e.g. if the resource passed through multiple systems on the way to the current system.  # noqa: E501

        :return: The external_identifier of this LogicalResourceMVO.
        :rtype: List[ExternalIdentifierMVO]
        """
        return self._external_identifier

    @external_identifier.setter
    def external_identifier(self, external_identifier: List[ExternalIdentifierMVO]):
        """Sets the external_identifier of this LogicalResourceMVO.

        An identification of this resource that is owned by or originates in a software system different from the current system. The structure identifies the system itself, the nature of the resource within the system and the unique ID of the resource within the system. It is anticipated that multiple external IDs can be held for a single resource, e.g. if the resource passed through multiple systems on the way to the current system.  # noqa: E501

        :param external_identifier: The external_identifier of this LogicalResourceMVO.
        :type external_identifier: List[ExternalIdentifierMVO]
        """

        self._external_identifier = external_identifier

    @property
    def value(self) -> str:
        """Gets the value of this LogicalResourceMVO.

        the value of the logical resource. E.g '0746712345' for  MSISDN's  # noqa: E501

        :return: The value of this LogicalResourceMVO.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this LogicalResourceMVO.

        the value of the logical resource. E.g '0746712345' for  MSISDN's  # noqa: E501

        :param value: The value of this LogicalResourceMVO.
        :type value: str
        """

        self._value = value
