from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.attachment_ref import AttachmentRef
from openapi_server.models.characteristic import Characteristic
from openapi_server.models.external_identifier import ExternalIdentifier
from openapi_server.models.feature import Feature
from openapi_server.models.intent_ref import IntentRef
from openapi_server.models.note import Note
from openapi_server.models.related_party_ref_or_party_role_ref import RelatedPartyRefOrPartyRoleRef
from openapi_server.models.related_place_ref import RelatedPlaceRef
from openapi_server.models.related_resource_order_item import RelatedResourceOrderItem
from openapi_server.models.resource_administrative_state_type import ResourceAdministrativeStateType
from openapi_server.models.resource_operational_state_type import ResourceOperationalStateType
from openapi_server.models.resource_ref_or_value import ResourceRefOrValue
from openapi_server.models.resource_relationship import ResourceRelationship
from openapi_server.models.resource_specification_ref import ResourceSpecificationRef
from openapi_server.models.resource_status_type import ResourceStatusType
from openapi_server.models.resource_usage_state_type import ResourceUsageStateType
from openapi_server.models.time_period import TimePeriod
from openapi_server import util

from openapi_server.models.attachment_ref import AttachmentRef  # noqa: E501
from openapi_server.models.characteristic import Characteristic  # noqa: E501
from openapi_server.models.external_identifier import ExternalIdentifier  # noqa: E501
from openapi_server.models.feature import Feature  # noqa: E501
from openapi_server.models.intent_ref import IntentRef  # noqa: E501
from openapi_server.models.note import Note  # noqa: E501
from openapi_server.models.related_party_ref_or_party_role_ref import RelatedPartyRefOrPartyRoleRef  # noqa: E501
from openapi_server.models.related_place_ref import RelatedPlaceRef  # noqa: E501
from openapi_server.models.related_resource_order_item import RelatedResourceOrderItem  # noqa: E501
from openapi_server.models.resource_administrative_state_type import ResourceAdministrativeStateType  # noqa: E501
from openapi_server.models.resource_operational_state_type import ResourceOperationalStateType  # noqa: E501
from openapi_server.models.resource_ref_or_value import ResourceRefOrValue  # noqa: E501
from openapi_server.models.resource_relationship import ResourceRelationship  # noqa: E501
from openapi_server.models.resource_specification_ref import ResourceSpecificationRef  # noqa: E501
from openapi_server.models.resource_status_type import ResourceStatusType  # noqa: E501
from openapi_server.models.resource_usage_state_type import ResourceUsageStateType  # noqa: E501
from openapi_server.models.time_period import TimePeriod  # noqa: E501

class Resource(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, base_type=None, schema_location=None, href=None, id=None, category=None, description=None, name=None, end_operating_date=None, administrative_state=None, operational_state=None, resource_status=None, usage_state=None, valid_for=None, note=None, resource_order_item=None, place=None, related_party=None, supporting_resource=None, resource_relationship=None, resource_characteristic=None, attachment=None, resource_specification=None, start_operating_date=None, resource_version=None, activation_feature=None, intent=None, external_identifier=None):  # noqa: E501
        """Resource - a model defined in OpenAPI

        :param type: The type of this Resource.  # noqa: E501
        :type type: str
        :param base_type: The base_type of this Resource.  # noqa: E501
        :type base_type: str
        :param schema_location: The schema_location of this Resource.  # noqa: E501
        :type schema_location: str
        :param href: The href of this Resource.  # noqa: E501
        :type href: str
        :param id: The id of this Resource.  # noqa: E501
        :type id: str
        :param category: The category of this Resource.  # noqa: E501
        :type category: str
        :param description: The description of this Resource.  # noqa: E501
        :type description: str
        :param name: The name of this Resource.  # noqa: E501
        :type name: str
        :param end_operating_date: The end_operating_date of this Resource.  # noqa: E501
        :type end_operating_date: datetime
        :param administrative_state: The administrative_state of this Resource.  # noqa: E501
        :type administrative_state: ResourceAdministrativeStateType
        :param operational_state: The operational_state of this Resource.  # noqa: E501
        :type operational_state: ResourceOperationalStateType
        :param resource_status: The resource_status of this Resource.  # noqa: E501
        :type resource_status: ResourceStatusType
        :param usage_state: The usage_state of this Resource.  # noqa: E501
        :type usage_state: ResourceUsageStateType
        :param valid_for: The valid_for of this Resource.  # noqa: E501
        :type valid_for: TimePeriod
        :param note: The note of this Resource.  # noqa: E501
        :type note: List[Note]
        :param resource_order_item: The resource_order_item of this Resource.  # noqa: E501
        :type resource_order_item: List[RelatedResourceOrderItem]
        :param place: The place of this Resource.  # noqa: E501
        :type place: List[RelatedPlaceRef]
        :param related_party: The related_party of this Resource.  # noqa: E501
        :type related_party: List[RelatedPartyRefOrPartyRoleRef]
        :param supporting_resource: The supporting_resource of this Resource.  # noqa: E501
        :type supporting_resource: List[ResourceRefOrValue]
        :param resource_relationship: The resource_relationship of this Resource.  # noqa: E501
        :type resource_relationship: List[ResourceRelationship]
        :param resource_characteristic: The resource_characteristic of this Resource.  # noqa: E501
        :type resource_characteristic: List[Characteristic]
        :param attachment: The attachment of this Resource.  # noqa: E501
        :type attachment: List[AttachmentRef]
        :param resource_specification: The resource_specification of this Resource.  # noqa: E501
        :type resource_specification: ResourceSpecificationRef
        :param start_operating_date: The start_operating_date of this Resource.  # noqa: E501
        :type start_operating_date: datetime
        :param resource_version: The resource_version of this Resource.  # noqa: E501
        :type resource_version: str
        :param activation_feature: The activation_feature of this Resource.  # noqa: E501
        :type activation_feature: List[Feature]
        :param intent: The intent of this Resource.  # noqa: E501
        :type intent: IntentRef
        :param external_identifier: The external_identifier of this Resource.  # noqa: E501
        :type external_identifier: List[ExternalIdentifier]
        """
        self.openapi_types = {
            'type': str,
            'base_type': str,
            'schema_location': str,
            'href': str,
            'id': str,
            'category': str,
            'description': str,
            'name': str,
            'end_operating_date': datetime,
            'administrative_state': ResourceAdministrativeStateType,
            'operational_state': ResourceOperationalStateType,
            'resource_status': ResourceStatusType,
            'usage_state': ResourceUsageStateType,
            'valid_for': TimePeriod,
            'note': List[Note],
            'resource_order_item': List[RelatedResourceOrderItem],
            'place': List[RelatedPlaceRef],
            'related_party': List[RelatedPartyRefOrPartyRoleRef],
            'supporting_resource': List[ResourceRefOrValue],
            'resource_relationship': List[ResourceRelationship],
            'resource_characteristic': List[Characteristic],
            'attachment': List[AttachmentRef],
            'resource_specification': ResourceSpecificationRef,
            'start_operating_date': datetime,
            'resource_version': str,
            'activation_feature': List[Feature],
            'intent': IntentRef,
            'external_identifier': List[ExternalIdentifier]
        }

        self.attribute_map = {
            'type': '@type',
            'base_type': '@baseType',
            'schema_location': '@schemaLocation',
            'href': 'href',
            'id': 'id',
            'category': 'category',
            'description': 'description',
            'name': 'name',
            'end_operating_date': 'endOperatingDate',
            'administrative_state': 'administrativeState',
            'operational_state': 'operationalState',
            'resource_status': 'resourceStatus',
            'usage_state': 'usageState',
            'valid_for': 'validFor',
            'note': 'note',
            'resource_order_item': 'resourceOrderItem',
            'place': 'place',
            'related_party': 'relatedParty',
            'supporting_resource': 'supportingResource',
            'resource_relationship': 'resourceRelationship',
            'resource_characteristic': 'resourceCharacteristic',
            'attachment': 'attachment',
            'resource_specification': 'resourceSpecification',
            'start_operating_date': 'startOperatingDate',
            'resource_version': 'resourceVersion',
            'activation_feature': 'activationFeature',
            'intent': 'intent',
            'external_identifier': 'externalIdentifier'
        }

        self._type = type
        self._base_type = base_type
        self._schema_location = schema_location
        self._href = href
        self._id = id
        self._category = category
        self._description = description
        self._name = name
        self._end_operating_date = end_operating_date
        self._administrative_state = administrative_state
        self._operational_state = operational_state
        self._resource_status = resource_status
        self._usage_state = usage_state
        self._valid_for = valid_for
        self._note = note
        self._resource_order_item = resource_order_item
        self._place = place
        self._related_party = related_party
        self._supporting_resource = supporting_resource
        self._resource_relationship = resource_relationship
        self._resource_characteristic = resource_characteristic
        self._attachment = attachment
        self._resource_specification = resource_specification
        self._start_operating_date = start_operating_date
        self._resource_version = resource_version
        self._activation_feature = activation_feature
        self._intent = intent
        self._external_identifier = external_identifier

    @classmethod
    def from_dict(cls, dikt) -> 'Resource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Resource of this Resource.  # noqa: E501
        :rtype: Resource
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this Resource.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :return: The type of this Resource.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Resource.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :param type: The type of this Resource.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def base_type(self) -> str:
        """Gets the base_type of this Resource.

        When sub-classing, this defines the super-class  # noqa: E501

        :return: The base_type of this Resource.
        :rtype: str
        """
        return self._base_type

    @base_type.setter
    def base_type(self, base_type: str):
        """Sets the base_type of this Resource.

        When sub-classing, this defines the super-class  # noqa: E501

        :param base_type: The base_type of this Resource.
        :type base_type: str
        """

        self._base_type = base_type

    @property
    def schema_location(self) -> str:
        """Gets the schema_location of this Resource.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :return: The schema_location of this Resource.
        :rtype: str
        """
        return self._schema_location

    @schema_location.setter
    def schema_location(self, schema_location: str):
        """Sets the schema_location of this Resource.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :param schema_location: The schema_location of this Resource.
        :type schema_location: str
        """

        self._schema_location = schema_location

    @property
    def href(self) -> str:
        """Gets the href of this Resource.

        Hyperlink reference  # noqa: E501

        :return: The href of this Resource.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this Resource.

        Hyperlink reference  # noqa: E501

        :param href: The href of this Resource.
        :type href: str
        """

        self._href = href

    @property
    def id(self) -> str:
        """Gets the id of this Resource.

        unique identifier  # noqa: E501

        :return: The id of this Resource.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Resource.

        unique identifier  # noqa: E501

        :param id: The id of this Resource.
        :type id: str
        """

        self._id = id

    @property
    def category(self) -> str:
        """Gets the category of this Resource.

        Category of the concrete resource. e.g Gold, Silver for MSISDN concrete resource  # noqa: E501

        :return: The category of this Resource.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this Resource.

        Category of the concrete resource. e.g Gold, Silver for MSISDN concrete resource  # noqa: E501

        :param category: The category of this Resource.
        :type category: str
        """

        self._category = category

    @property
    def description(self) -> str:
        """Gets the description of this Resource.

        free-text description of the resource  # noqa: E501

        :return: The description of this Resource.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Resource.

        free-text description of the resource  # noqa: E501

        :param description: The description of this Resource.
        :type description: str
        """

        self._description = description

    @property
    def name(self) -> str:
        """Gets the name of this Resource.

        the name of the resource  # noqa: E501

        :return: The name of this Resource.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Resource.

        the name of the resource  # noqa: E501

        :param name: The name of this Resource.
        :type name: str
        """

        self._name = name

    @property
    def end_operating_date(self) -> datetime:
        """Gets the end_operating_date of this Resource.

        A date time( DateTime). The date till the resource is operating  # noqa: E501

        :return: The end_operating_date of this Resource.
        :rtype: datetime
        """
        return self._end_operating_date

    @end_operating_date.setter
    def end_operating_date(self, end_operating_date: datetime):
        """Sets the end_operating_date of this Resource.

        A date time( DateTime). The date till the resource is operating  # noqa: E501

        :param end_operating_date: The end_operating_date of this Resource.
        :type end_operating_date: datetime
        """

        self._end_operating_date = end_operating_date

    @property
    def administrative_state(self) -> ResourceAdministrativeStateType:
        """Gets the administrative_state of this Resource.


        :return: The administrative_state of this Resource.
        :rtype: ResourceAdministrativeStateType
        """
        return self._administrative_state

    @administrative_state.setter
    def administrative_state(self, administrative_state: ResourceAdministrativeStateType):
        """Sets the administrative_state of this Resource.


        :param administrative_state: The administrative_state of this Resource.
        :type administrative_state: ResourceAdministrativeStateType
        """

        self._administrative_state = administrative_state

    @property
    def operational_state(self) -> ResourceOperationalStateType:
        """Gets the operational_state of this Resource.


        :return: The operational_state of this Resource.
        :rtype: ResourceOperationalStateType
        """
        return self._operational_state

    @operational_state.setter
    def operational_state(self, operational_state: ResourceOperationalStateType):
        """Sets the operational_state of this Resource.


        :param operational_state: The operational_state of this Resource.
        :type operational_state: ResourceOperationalStateType
        """

        self._operational_state = operational_state

    @property
    def resource_status(self) -> ResourceStatusType:
        """Gets the resource_status of this Resource.


        :return: The resource_status of this Resource.
        :rtype: ResourceStatusType
        """
        return self._resource_status

    @resource_status.setter
    def resource_status(self, resource_status: ResourceStatusType):
        """Sets the resource_status of this Resource.


        :param resource_status: The resource_status of this Resource.
        :type resource_status: ResourceStatusType
        """

        self._resource_status = resource_status

    @property
    def usage_state(self) -> ResourceUsageStateType:
        """Gets the usage_state of this Resource.


        :return: The usage_state of this Resource.
        :rtype: ResourceUsageStateType
        """
        return self._usage_state

    @usage_state.setter
    def usage_state(self, usage_state: ResourceUsageStateType):
        """Sets the usage_state of this Resource.


        :param usage_state: The usage_state of this Resource.
        :type usage_state: ResourceUsageStateType
        """

        self._usage_state = usage_state

    @property
    def valid_for(self) -> TimePeriod:
        """Gets the valid_for of this Resource.


        :return: The valid_for of this Resource.
        :rtype: TimePeriod
        """
        return self._valid_for

    @valid_for.setter
    def valid_for(self, valid_for: TimePeriod):
        """Sets the valid_for of this Resource.


        :param valid_for: The valid_for of this Resource.
        :type valid_for: TimePeriod
        """

        self._valid_for = valid_for

    @property
    def note(self) -> List[Note]:
        """Gets the note of this Resource.


        :return: The note of this Resource.
        :rtype: List[Note]
        """
        return self._note

    @note.setter
    def note(self, note: List[Note]):
        """Sets the note of this Resource.


        :param note: The note of this Resource.
        :type note: List[Note]
        """

        self._note = note

    @property
    def resource_order_item(self) -> List[RelatedResourceOrderItem]:
        """Gets the resource_order_item of this Resource.

        A list of resource order items related to this resource  # noqa: E501

        :return: The resource_order_item of this Resource.
        :rtype: List[RelatedResourceOrderItem]
        """
        return self._resource_order_item

    @resource_order_item.setter
    def resource_order_item(self, resource_order_item: List[RelatedResourceOrderItem]):
        """Sets the resource_order_item of this Resource.

        A list of resource order items related to this resource  # noqa: E501

        :param resource_order_item: The resource_order_item of this Resource.
        :type resource_order_item: List[RelatedResourceOrderItem]
        """

        self._resource_order_item = resource_order_item

    @property
    def place(self) -> List[RelatedPlaceRef]:
        """Gets the place of this Resource.


        :return: The place of this Resource.
        :rtype: List[RelatedPlaceRef]
        """
        return self._place

    @place.setter
    def place(self, place: List[RelatedPlaceRef]):
        """Sets the place of this Resource.


        :param place: The place of this Resource.
        :type place: List[RelatedPlaceRef]
        """

        self._place = place

    @property
    def related_party(self) -> List[RelatedPartyRefOrPartyRoleRef]:
        """Gets the related_party of this Resource.


        :return: The related_party of this Resource.
        :rtype: List[RelatedPartyRefOrPartyRoleRef]
        """
        return self._related_party

    @related_party.setter
    def related_party(self, related_party: List[RelatedPartyRefOrPartyRoleRef]):
        """Sets the related_party of this Resource.


        :param related_party: The related_party of this Resource.
        :type related_party: List[RelatedPartyRefOrPartyRoleRef]
        """

        self._related_party = related_party

    @property
    def supporting_resource(self) -> List[ResourceRefOrValue]:
        """Gets the supporting_resource of this Resource.

        A list of supporting resources (SupportingResource [*]). A collection of resources that support this resource (bundling, link ResourceSpecification)  # noqa: E501

        :return: The supporting_resource of this Resource.
        :rtype: List[ResourceRefOrValue]
        """
        return self._supporting_resource

    @supporting_resource.setter
    def supporting_resource(self, supporting_resource: List[ResourceRefOrValue]):
        """Sets the supporting_resource of this Resource.

        A list of supporting resources (SupportingResource [*]). A collection of resources that support this resource (bundling, link ResourceSpecification)  # noqa: E501

        :param supporting_resource: The supporting_resource of this Resource.
        :type supporting_resource: List[ResourceRefOrValue]
        """

        self._supporting_resource = supporting_resource

    @property
    def resource_relationship(self) -> List[ResourceRelationship]:
        """Gets the resource_relationship of this Resource.


        :return: The resource_relationship of this Resource.
        :rtype: List[ResourceRelationship]
        """
        return self._resource_relationship

    @resource_relationship.setter
    def resource_relationship(self, resource_relationship: List[ResourceRelationship]):
        """Sets the resource_relationship of this Resource.


        :param resource_relationship: The resource_relationship of this Resource.
        :type resource_relationship: List[ResourceRelationship]
        """

        self._resource_relationship = resource_relationship

    @property
    def resource_characteristic(self) -> List[Characteristic]:
        """Gets the resource_characteristic of this Resource.


        :return: The resource_characteristic of this Resource.
        :rtype: List[Characteristic]
        """
        return self._resource_characteristic

    @resource_characteristic.setter
    def resource_characteristic(self, resource_characteristic: List[Characteristic]):
        """Sets the resource_characteristic of this Resource.


        :param resource_characteristic: The resource_characteristic of this Resource.
        :type resource_characteristic: List[Characteristic]
        """

        self._resource_characteristic = resource_characteristic

    @property
    def attachment(self) -> List[AttachmentRef]:
        """Gets the attachment of this Resource.


        :return: The attachment of this Resource.
        :rtype: List[AttachmentRef]
        """
        return self._attachment

    @attachment.setter
    def attachment(self, attachment: List[AttachmentRef]):
        """Sets the attachment of this Resource.


        :param attachment: The attachment of this Resource.
        :type attachment: List[AttachmentRef]
        """

        self._attachment = attachment

    @property
    def resource_specification(self) -> ResourceSpecificationRef:
        """Gets the resource_specification of this Resource.


        :return: The resource_specification of this Resource.
        :rtype: ResourceSpecificationRef
        """
        return self._resource_specification

    @resource_specification.setter
    def resource_specification(self, resource_specification: ResourceSpecificationRef):
        """Sets the resource_specification of this Resource.


        :param resource_specification: The resource_specification of this Resource.
        :type resource_specification: ResourceSpecificationRef
        """

        self._resource_specification = resource_specification

    @property
    def start_operating_date(self) -> datetime:
        """Gets the start_operating_date of this Resource.

        A date time( DateTime). The date from which the resource is operating  # noqa: E501

        :return: The start_operating_date of this Resource.
        :rtype: datetime
        """
        return self._start_operating_date

    @start_operating_date.setter
    def start_operating_date(self, start_operating_date: datetime):
        """Sets the start_operating_date of this Resource.

        A date time( DateTime). The date from which the resource is operating  # noqa: E501

        :param start_operating_date: The start_operating_date of this Resource.
        :type start_operating_date: datetime
        """

        self._start_operating_date = start_operating_date

    @property
    def resource_version(self) -> str:
        """Gets the resource_version of this Resource.

        A field that identifies the specific version of an instance of a resource.  # noqa: E501

        :return: The resource_version of this Resource.
        :rtype: str
        """
        return self._resource_version

    @resource_version.setter
    def resource_version(self, resource_version: str):
        """Sets the resource_version of this Resource.

        A field that identifies the specific version of an instance of a resource.  # noqa: E501

        :param resource_version: The resource_version of this Resource.
        :type resource_version: str
        """

        self._resource_version = resource_version

    @property
    def activation_feature(self) -> List[Feature]:
        """Gets the activation_feature of this Resource.

        Configuration features  # noqa: E501

        :return: The activation_feature of this Resource.
        :rtype: List[Feature]
        """
        return self._activation_feature

    @activation_feature.setter
    def activation_feature(self, activation_feature: List[Feature]):
        """Sets the activation_feature of this Resource.

        Configuration features  # noqa: E501

        :param activation_feature: The activation_feature of this Resource.
        :type activation_feature: List[Feature]
        """

        self._activation_feature = activation_feature

    @property
    def intent(self) -> IntentRef:
        """Gets the intent of this Resource.


        :return: The intent of this Resource.
        :rtype: IntentRef
        """
        return self._intent

    @intent.setter
    def intent(self, intent: IntentRef):
        """Sets the intent of this Resource.


        :param intent: The intent of this Resource.
        :type intent: IntentRef
        """

        self._intent = intent

    @property
    def external_identifier(self) -> List[ExternalIdentifier]:
        """Gets the external_identifier of this Resource.

        An identification of this resource that is owned by or originates in a software system different from the current system. The structure identifies the system itself, the nature of the resource within the system and the unique ID of the resource within the system. It is anticipated that multiple external IDs can be held for a single resource, e.g. if the resource passed through multiple systems on the way to the current system.  # noqa: E501

        :return: The external_identifier of this Resource.
        :rtype: List[ExternalIdentifier]
        """
        return self._external_identifier

    @external_identifier.setter
    def external_identifier(self, external_identifier: List[ExternalIdentifier]):
        """Sets the external_identifier of this Resource.

        An identification of this resource that is owned by or originates in a software system different from the current system. The structure identifies the system itself, the nature of the resource within the system and the unique ID of the resource within the system. It is anticipated that multiple external IDs can be held for a single resource, e.g. if the resource passed through multiple systems on the way to the current system.  # noqa: E501

        :param external_identifier: The external_identifier of this Resource.
        :type external_identifier: List[ExternalIdentifier]
        """

        self._external_identifier = external_identifier
