/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.19.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Error;
import org.openapitools.model.PartyRoleAttributeValueChangeEvent;
import org.openapitools.model.PartyRoleCreateEvent;
import org.openapitools.model.PartyRoleDeleteEvent;
import org.openapitools.model.PartyRoleSpecificationAttributeValueChangeEvent;
import org.openapitools.model.PartyRoleSpecificationCreateEvent;
import org.openapitools.model.PartyRoleSpecificationDeleteEvent;
import org.openapitools.model.PartyRoleSpecificationStateChangeEvent;
import org.openapitools.model.PartyRoleStateChangeEvent;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-07T14:50:00.575868917+01:00[Europe/Paris]", comments = "Generator version: 7.19.0-SNAPSHOT")
@Validated
@Tag(name = "notification listener", description = "Notifications for Resource Lifecycle and event notifications")
public interface ListenerApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_PARTY_ROLE_ATTRIBUTE_VALUE_CHANGE_EVENT = "/listener/partyRoleAttributeValueChangeEvent";
    /**
     * POST /listener/partyRoleAttributeValueChangeEvent : Client listener for entity PartyRoleAttributeValueChangeEvent
     * Example of a client listener for receiving the notification PartyRoleAttributeValueChangeEvent
     *
     * @param partyRoleAttributeValueChangeEvent PartyRole attributeValueChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "partyRoleAttributeValueChangeEvent",
        summary = "Client listener for entity PartyRoleAttributeValueChangeEvent",
        description = "Example of a client listener for receiving the notification PartyRoleAttributeValueChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_PARTY_ROLE_ATTRIBUTE_VALUE_CHANGE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> partyRoleAttributeValueChangeEvent(
        @Parameter(name = "PartyRoleAttributeValueChangeEvent", description = "PartyRole attributeValueChange Event payload", required = true) @Valid @RequestBody PartyRoleAttributeValueChangeEvent partyRoleAttributeValueChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_PARTY_ROLE_CREATE_EVENT = "/listener/partyRoleCreateEvent";
    /**
     * POST /listener/partyRoleCreateEvent : Client listener for entity PartyRoleCreateEvent
     * Example of a client listener for receiving the notification PartyRoleCreateEvent
     *
     * @param partyRoleCreateEvent PartyRole create Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "partyRoleCreateEvent",
        summary = "Client listener for entity PartyRoleCreateEvent",
        description = "Example of a client listener for receiving the notification PartyRoleCreateEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_PARTY_ROLE_CREATE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> partyRoleCreateEvent(
        @Parameter(name = "PartyRoleCreateEvent", description = "PartyRole create Event payload", required = true) @Valid @RequestBody PartyRoleCreateEvent partyRoleCreateEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_PARTY_ROLE_DELETE_EVENT = "/listener/partyRoleDeleteEvent";
    /**
     * POST /listener/partyRoleDeleteEvent : Client listener for entity PartyRoleDeleteEvent
     * Example of a client listener for receiving the notification PartyRoleDeleteEvent
     *
     * @param partyRoleDeleteEvent PartyRole delete Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "partyRoleDeleteEvent",
        summary = "Client listener for entity PartyRoleDeleteEvent",
        description = "Example of a client listener for receiving the notification PartyRoleDeleteEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_PARTY_ROLE_DELETE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> partyRoleDeleteEvent(
        @Parameter(name = "PartyRoleDeleteEvent", description = "PartyRole delete Event payload", required = true) @Valid @RequestBody PartyRoleDeleteEvent partyRoleDeleteEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_PARTY_ROLE_SPECIFICATION_ATTRIBUTE_VALUE_CHANGE_EVENT = "/listener/partyRoleSpecificationAttributeValueChangeEvent";
    /**
     * POST /listener/partyRoleSpecificationAttributeValueChangeEvent : Client listener for entity PartyRoleSpecificationAttributeValueChangeEvent
     * Example of a client listener for receiving the notification PartyRoleSpecificationAttributeValueChangeEvent
     *
     * @param partyRoleSpecificationAttributeValueChangeEvent PartyRoleSpecification attributeValueChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "partyRoleSpecificationAttributeValueChangeEvent",
        summary = "Client listener for entity PartyRoleSpecificationAttributeValueChangeEvent",
        description = "Example of a client listener for receiving the notification PartyRoleSpecificationAttributeValueChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_PARTY_ROLE_SPECIFICATION_ATTRIBUTE_VALUE_CHANGE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> partyRoleSpecificationAttributeValueChangeEvent(
        @Parameter(name = "PartyRoleSpecificationAttributeValueChangeEvent", description = "PartyRoleSpecification attributeValueChange Event payload", required = true) @Valid @RequestBody PartyRoleSpecificationAttributeValueChangeEvent partyRoleSpecificationAttributeValueChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_PARTY_ROLE_SPECIFICATION_CREATE_EVENT = "/listener/partyRoleSpecificationCreateEvent";
    /**
     * POST /listener/partyRoleSpecificationCreateEvent : Client listener for entity PartyRoleSpecificationCreateEvent
     * Example of a client listener for receiving the notification PartyRoleSpecificationCreateEvent
     *
     * @param partyRoleSpecificationCreateEvent PartyRoleSpecification create Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "partyRoleSpecificationCreateEvent",
        summary = "Client listener for entity PartyRoleSpecificationCreateEvent",
        description = "Example of a client listener for receiving the notification PartyRoleSpecificationCreateEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_PARTY_ROLE_SPECIFICATION_CREATE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> partyRoleSpecificationCreateEvent(
        @Parameter(name = "PartyRoleSpecificationCreateEvent", description = "PartyRoleSpecification create Event payload", required = true) @Valid @RequestBody PartyRoleSpecificationCreateEvent partyRoleSpecificationCreateEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_PARTY_ROLE_SPECIFICATION_DELETE_EVENT = "/listener/partyRoleSpecificationDeleteEvent";
    /**
     * POST /listener/partyRoleSpecificationDeleteEvent : Client listener for entity PartyRoleSpecificationDeleteEvent
     * Example of a client listener for receiving the notification PartyRoleSpecificationDeleteEvent
     *
     * @param partyRoleSpecificationDeleteEvent PartyRoleSpecification delete Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "partyRoleSpecificationDeleteEvent",
        summary = "Client listener for entity PartyRoleSpecificationDeleteEvent",
        description = "Example of a client listener for receiving the notification PartyRoleSpecificationDeleteEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_PARTY_ROLE_SPECIFICATION_DELETE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> partyRoleSpecificationDeleteEvent(
        @Parameter(name = "PartyRoleSpecificationDeleteEvent", description = "PartyRoleSpecification delete Event payload", required = true) @Valid @RequestBody PartyRoleSpecificationDeleteEvent partyRoleSpecificationDeleteEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_PARTY_ROLE_SPECIFICATION_STATE_CHANGE_EVENT = "/listener/partyRoleSpecificationStateChangeEvent";
    /**
     * POST /listener/partyRoleSpecificationStateChangeEvent : Client listener for entity PartyRoleSpecificationStateChangeEvent
     * Example of a client listener for receiving the notification PartyRoleSpecificationStateChangeEvent
     *
     * @param partyRoleSpecificationStateChangeEvent PartyRoleSpecification stateChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "partyRoleSpecificationStateChangeEvent",
        summary = "Client listener for entity PartyRoleSpecificationStateChangeEvent",
        description = "Example of a client listener for receiving the notification PartyRoleSpecificationStateChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_PARTY_ROLE_SPECIFICATION_STATE_CHANGE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> partyRoleSpecificationStateChangeEvent(
        @Parameter(name = "PartyRoleSpecificationStateChangeEvent", description = "PartyRoleSpecification stateChange Event payload", required = true) @Valid @RequestBody PartyRoleSpecificationStateChangeEvent partyRoleSpecificationStateChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_PARTY_ROLE_STATE_CHANGE_EVENT = "/listener/partyRoleStateChangeEvent";
    /**
     * POST /listener/partyRoleStateChangeEvent : Client listener for entity PartyRoleStateChangeEvent
     * Example of a client listener for receiving the notification PartyRoleStateChangeEvent
     *
     * @param partyRoleStateChangeEvent PartyRole stateChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "partyRoleStateChangeEvent",
        summary = "Client listener for entity PartyRoleStateChangeEvent",
        description = "Example of a client listener for receiving the notification PartyRoleStateChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_PARTY_ROLE_STATE_CHANGE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> partyRoleStateChangeEvent(
        @Parameter(name = "PartyRoleStateChangeEvent", description = "PartyRole stateChange Event payload", required = true) @Valid @RequestBody PartyRoleStateChangeEvent partyRoleStateChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
