/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.19.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.CheckCredentialCreateEvent;
import org.openapitools.model.CheckCredentialStateChangeEvent;
import org.openapitools.model.CredentialAttributeValueChangeEvent;
import org.openapitools.model.CredentialCreateEvent;
import org.openapitools.model.CredentialDeleteEvent;
import org.openapitools.model.CredentialStateChangeEvent;
import org.openapitools.model.DigitalIdentityAttributeValueChangeEvent;
import org.openapitools.model.DigitalIdentityCreateEvent;
import org.openapitools.model.DigitalIdentityDeleteEvent;
import org.openapitools.model.DigitalIdentityStateChangeEvent;
import org.openapitools.model.Error;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-07T14:50:13.349318156+01:00[Europe/Paris]", comments = "Generator version: 7.19.0-SNAPSHOT")
@Validated
@Tag(name = "notification listener", description = "Notifications for Resource Lifecycle and event notifications")
public interface ListenerApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CHECK_CREDENTIAL_CREATE_EVENT = "/listener/checkCredentialCreateEvent";
    /**
     * POST /listener/checkCredentialCreateEvent : Client listener for entity CheckCredentialCreateEvent
     * Example of a client listener for receiving the notification CheckCredentialCreateEvent
     *
     * @param checkCredentialCreateEvent CheckCredential create Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "checkCredentialCreateEvent",
        summary = "Client listener for entity CheckCredentialCreateEvent",
        description = "Example of a client listener for receiving the notification CheckCredentialCreateEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"@type\":\"Error\",\"code\":\"ERR001\",\"reason\":\"Missing information\",\"message\":\"Please provide the additional example information\",\"referenceError\":\"https://host/errors\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_CHECK_CREDENTIAL_CREATE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> checkCredentialCreateEvent(
        @Parameter(name = "CheckCredentialCreateEvent", description = "CheckCredential create Event payload", required = true) @Valid @RequestBody CheckCredentialCreateEvent checkCredentialCreateEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CHECK_CREDENTIAL_STATE_CHANGE_EVENT = "/listener/checkCredentialStateChangeEvent";
    /**
     * POST /listener/checkCredentialStateChangeEvent : Client listener for entity CheckCredentialStateChangeEvent
     * Example of a client listener for receiving the notification CheckCredentialStateChangeEvent
     *
     * @param checkCredentialStateChangeEvent CheckCredential stateChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "checkCredentialStateChangeEvent",
        summary = "Client listener for entity CheckCredentialStateChangeEvent",
        description = "Example of a client listener for receiving the notification CheckCredentialStateChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"@type\":\"Error\",\"code\":\"ERR001\",\"reason\":\"Missing information\",\"message\":\"Please provide the additional example information\",\"referenceError\":\"https://host/errors\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_CHECK_CREDENTIAL_STATE_CHANGE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> checkCredentialStateChangeEvent(
        @Parameter(name = "CheckCredentialStateChangeEvent", description = "CheckCredential stateChange Event payload", required = true) @Valid @RequestBody CheckCredentialStateChangeEvent checkCredentialStateChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREDENTIAL_ATTRIBUTE_VALUE_CHANGE_EVENT = "/listener/credentialAttributeValueChangeEvent";
    /**
     * POST /listener/credentialAttributeValueChangeEvent : Client listener for entity CredentialAttributeValueChangeEvent
     * Example of a client listener for receiving the notification CredentialAttributeValueChangeEvent
     *
     * @param credentialAttributeValueChangeEvent Credential attributeValueChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "credentialAttributeValueChangeEvent",
        summary = "Client listener for entity CredentialAttributeValueChangeEvent",
        description = "Example of a client listener for receiving the notification CredentialAttributeValueChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"@type\":\"Error\",\"code\":\"ERR001\",\"reason\":\"Missing information\",\"message\":\"Please provide the additional example information\",\"referenceError\":\"https://host/errors\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_CREDENTIAL_ATTRIBUTE_VALUE_CHANGE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> credentialAttributeValueChangeEvent(
        @Parameter(name = "CredentialAttributeValueChangeEvent", description = "Credential attributeValueChange Event payload", required = true) @Valid @RequestBody CredentialAttributeValueChangeEvent credentialAttributeValueChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREDENTIAL_CREATE_EVENT = "/listener/credentialCreateEvent";
    /**
     * POST /listener/credentialCreateEvent : Client listener for entity CredentialCreateEvent
     * Example of a client listener for receiving the notification CredentialCreateEvent
     *
     * @param credentialCreateEvent Credential create Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "credentialCreateEvent",
        summary = "Client listener for entity CredentialCreateEvent",
        description = "Example of a client listener for receiving the notification CredentialCreateEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"@type\":\"Error\",\"code\":\"ERR001\",\"reason\":\"Missing information\",\"message\":\"Please provide the additional example information\",\"referenceError\":\"https://host/errors\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_CREDENTIAL_CREATE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> credentialCreateEvent(
        @Parameter(name = "CredentialCreateEvent", description = "Credential create Event payload", required = true) @Valid @RequestBody CredentialCreateEvent credentialCreateEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREDENTIAL_DELETE_EVENT = "/listener/credentialDeleteEvent";
    /**
     * POST /listener/credentialDeleteEvent : Client listener for entity CredentialDeleteEvent
     * Example of a client listener for receiving the notification CredentialDeleteEvent
     *
     * @param credentialDeleteEvent Credential delete Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "credentialDeleteEvent",
        summary = "Client listener for entity CredentialDeleteEvent",
        description = "Example of a client listener for receiving the notification CredentialDeleteEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"@type\":\"Error\",\"code\":\"ERR001\",\"reason\":\"Missing information\",\"message\":\"Please provide the additional example information\",\"referenceError\":\"https://host/errors\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_CREDENTIAL_DELETE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> credentialDeleteEvent(
        @Parameter(name = "CredentialDeleteEvent", description = "Credential delete Event payload", required = true) @Valid @RequestBody CredentialDeleteEvent credentialDeleteEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREDENTIAL_STATE_CHANGE_EVENT = "/listener/credentialStateChangeEvent";
    /**
     * POST /listener/credentialStateChangeEvent : Client listener for entity CredentialStateChangeEvent
     * Example of a client listener for receiving the notification CredentialStateChangeEvent
     *
     * @param credentialStateChangeEvent Credential stateChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "credentialStateChangeEvent",
        summary = "Client listener for entity CredentialStateChangeEvent",
        description = "Example of a client listener for receiving the notification CredentialStateChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"@type\":\"Error\",\"code\":\"ERR001\",\"reason\":\"Missing information\",\"message\":\"Please provide the additional example information\",\"referenceError\":\"https://host/errors\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_CREDENTIAL_STATE_CHANGE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> credentialStateChangeEvent(
        @Parameter(name = "CredentialStateChangeEvent", description = "Credential stateChange Event payload", required = true) @Valid @RequestBody CredentialStateChangeEvent credentialStateChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DIGITAL_IDENTITY_ATTRIBUTE_VALUE_CHANGE_EVENT = "/listener/digitalIdentityAttributeValueChangeEvent";
    /**
     * POST /listener/digitalIdentityAttributeValueChangeEvent : Client listener for entity DigitalIdentityAttributeValueChangeEvent
     * Example of a client listener for receiving the notification DigitalIdentityAttributeValueChangeEvent
     *
     * @param digitalIdentityAttributeValueChangeEvent DigitalIdentity attributeValueChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "digitalIdentityAttributeValueChangeEvent",
        summary = "Client listener for entity DigitalIdentityAttributeValueChangeEvent",
        description = "Example of a client listener for receiving the notification DigitalIdentityAttributeValueChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"@type\":\"Error\",\"code\":\"ERR001\",\"reason\":\"Missing information\",\"message\":\"Please provide the additional example information\",\"referenceError\":\"https://host/errors\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_DIGITAL_IDENTITY_ATTRIBUTE_VALUE_CHANGE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> digitalIdentityAttributeValueChangeEvent(
        @Parameter(name = "DigitalIdentityAttributeValueChangeEvent", description = "DigitalIdentity attributeValueChange Event payload", required = true) @Valid @RequestBody DigitalIdentityAttributeValueChangeEvent digitalIdentityAttributeValueChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DIGITAL_IDENTITY_CREATE_EVENT = "/listener/digitalIdentityCreateEvent";
    /**
     * POST /listener/digitalIdentityCreateEvent : Client listener for entity DigitalIdentityCreateEvent
     * Example of a client listener for receiving the notification DigitalIdentityCreateEvent
     *
     * @param digitalIdentityCreateEvent DigitalIdentity create Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "digitalIdentityCreateEvent",
        summary = "Client listener for entity DigitalIdentityCreateEvent",
        description = "Example of a client listener for receiving the notification DigitalIdentityCreateEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"@type\":\"Error\",\"code\":\"ERR001\",\"reason\":\"Missing information\",\"message\":\"Please provide the additional example information\",\"referenceError\":\"https://host/errors\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_DIGITAL_IDENTITY_CREATE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> digitalIdentityCreateEvent(
        @Parameter(name = "DigitalIdentityCreateEvent", description = "DigitalIdentity create Event payload", required = true) @Valid @RequestBody DigitalIdentityCreateEvent digitalIdentityCreateEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DIGITAL_IDENTITY_DELETE_EVENT = "/listener/digitalIdentityDeleteEvent";
    /**
     * POST /listener/digitalIdentityDeleteEvent : Client listener for entity DigitalIdentityDeleteEvent
     * Example of a client listener for receiving the notification DigitalIdentityDeleteEvent
     *
     * @param digitalIdentityDeleteEvent DigitalIdentity delete Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "digitalIdentityDeleteEvent",
        summary = "Client listener for entity DigitalIdentityDeleteEvent",
        description = "Example of a client listener for receiving the notification DigitalIdentityDeleteEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"@type\":\"Error\",\"code\":\"ERR001\",\"reason\":\"Missing information\",\"message\":\"Please provide the additional example information\",\"referenceError\":\"https://host/errors\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_DIGITAL_IDENTITY_DELETE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> digitalIdentityDeleteEvent(
        @Parameter(name = "DigitalIdentityDeleteEvent", description = "DigitalIdentity delete Event payload", required = true) @Valid @RequestBody DigitalIdentityDeleteEvent digitalIdentityDeleteEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DIGITAL_IDENTITY_STATE_CHANGE_EVENT = "/listener/digitalIdentityStateChangeEvent";
    /**
     * POST /listener/digitalIdentityStateChangeEvent : Client listener for entity DigitalIdentityStateChangeEvent
     * Example of a client listener for receiving the notification DigitalIdentityStateChangeEvent
     *
     * @param digitalIdentityStateChangeEvent DigitalIdentity stateChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "digitalIdentityStateChangeEvent",
        summary = "Client listener for entity DigitalIdentityStateChangeEvent",
        description = "Example of a client listener for receiving the notification DigitalIdentityStateChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"@type\":\"Error\",\"code\":\"ERR001\",\"reason\":\"Missing information\",\"message\":\"Please provide the additional example information\",\"referenceError\":\"https://host/errors\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_DIGITAL_IDENTITY_STATE_CHANGE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> digitalIdentityStateChangeEvent(
        @Parameter(name = "DigitalIdentityStateChangeEvent", description = "DigitalIdentity stateChange Event payload", required = true) @Valid @RequestBody DigitalIdentityStateChangeEvent digitalIdentityStateChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
