from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.entity_ref import EntityRef
from openapi_server.models.related_party_ref_or_party_role_ref import RelatedPartyRefOrPartyRoleRef
from openapi_server import util

from openapi_server.models.entity_ref import EntityRef  # noqa: E501
from openapi_server.models.related_party_ref_or_party_role_ref import RelatedPartyRefOrPartyRoleRef  # noqa: E501

class ContextUpdate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, base_type=None, schema_location=None, id=None, last_update=None, reason=None, related_entity=None, related_party=None):  # noqa: E501
        """ContextUpdate - a model defined in OpenAPI

        :param type: The type of this ContextUpdate.  # noqa: E501
        :type type: str
        :param base_type: The base_type of this ContextUpdate.  # noqa: E501
        :type base_type: str
        :param schema_location: The schema_location of this ContextUpdate.  # noqa: E501
        :type schema_location: str
        :param id: The id of this ContextUpdate.  # noqa: E501
        :type id: str
        :param last_update: The last_update of this ContextUpdate.  # noqa: E501
        :type last_update: datetime
        :param reason: The reason of this ContextUpdate.  # noqa: E501
        :type reason: str
        :param related_entity: The related_entity of this ContextUpdate.  # noqa: E501
        :type related_entity: List[EntityRef]
        :param related_party: The related_party of this ContextUpdate.  # noqa: E501
        :type related_party: List[RelatedPartyRefOrPartyRoleRef]
        """
        self.openapi_types = {
            'type': str,
            'base_type': str,
            'schema_location': str,
            'id': str,
            'last_update': datetime,
            'reason': str,
            'related_entity': List[EntityRef],
            'related_party': List[RelatedPartyRefOrPartyRoleRef]
        }

        self.attribute_map = {
            'type': '@type',
            'base_type': '@baseType',
            'schema_location': '@schemaLocation',
            'id': 'id',
            'last_update': 'lastUpdate',
            'reason': 'reason',
            'related_entity': 'relatedEntity',
            'related_party': 'relatedParty'
        }

        self._type = type
        self._base_type = base_type
        self._schema_location = schema_location
        self._id = id
        self._last_update = last_update
        self._reason = reason
        self._related_entity = related_entity
        self._related_party = related_party

    @classmethod
    def from_dict(cls, dikt) -> 'ContextUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ContextUpdate of this ContextUpdate.  # noqa: E501
        :rtype: ContextUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ContextUpdate.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :return: The type of this ContextUpdate.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ContextUpdate.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :param type: The type of this ContextUpdate.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def base_type(self) -> str:
        """Gets the base_type of this ContextUpdate.

        When sub-classing, this defines the super-class  # noqa: E501

        :return: The base_type of this ContextUpdate.
        :rtype: str
        """
        return self._base_type

    @base_type.setter
    def base_type(self, base_type: str):
        """Sets the base_type of this ContextUpdate.

        When sub-classing, this defines the super-class  # noqa: E501

        :param base_type: The base_type of this ContextUpdate.
        :type base_type: str
        """

        self._base_type = base_type

    @property
    def schema_location(self) -> str:
        """Gets the schema_location of this ContextUpdate.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :return: The schema_location of this ContextUpdate.
        :rtype: str
        """
        return self._schema_location

    @schema_location.setter
    def schema_location(self, schema_location: str):
        """Sets the schema_location of this ContextUpdate.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :param schema_location: The schema_location of this ContextUpdate.
        :type schema_location: str
        """

        self._schema_location = schema_location

    @property
    def id(self) -> str:
        """Gets the id of this ContextUpdate.

        Identifier of the context update  # noqa: E501

        :return: The id of this ContextUpdate.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ContextUpdate.

        Identifier of the context update  # noqa: E501

        :param id: The id of this ContextUpdate.
        :type id: str
        """

        self._id = id

    @property
    def last_update(self) -> datetime:
        """Gets the last_update of this ContextUpdate.

        The date and time the status/state last changed.  # noqa: E501

        :return: The last_update of this ContextUpdate.
        :rtype: datetime
        """
        return self._last_update

    @last_update.setter
    def last_update(self, last_update: datetime):
        """Sets the last_update of this ContextUpdate.

        The date and time the status/state last changed.  # noqa: E501

        :param last_update: The last_update of this ContextUpdate.
        :type last_update: datetime
        """

        self._last_update = last_update

    @property
    def reason(self) -> str:
        """Gets the reason of this ContextUpdate.

        The reason/context for the current value of the status/state.  # noqa: E501

        :return: The reason of this ContextUpdate.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason: str):
        """Sets the reason of this ContextUpdate.

        The reason/context for the current value of the status/state.  # noqa: E501

        :param reason: The reason of this ContextUpdate.
        :type reason: str
        """

        self._reason = reason

    @property
    def related_entity(self) -> List[EntityRef]:
        """Gets the related_entity of this ContextUpdate.

        A list of entities that represent observations, anomalies or managing entities etc associated to the current status/state value.  # noqa: E501

        :return: The related_entity of this ContextUpdate.
        :rtype: List[EntityRef]
        """
        return self._related_entity

    @related_entity.setter
    def related_entity(self, related_entity: List[EntityRef]):
        """Sets the related_entity of this ContextUpdate.

        A list of entities that represent observations, anomalies or managing entities etc associated to the current status/state value.  # noqa: E501

        :param related_entity: The related_entity of this ContextUpdate.
        :type related_entity: List[EntityRef]
        """

        self._related_entity = related_entity

    @property
    def related_party(self) -> List[RelatedPartyRefOrPartyRoleRef]:
        """Gets the related_party of this ContextUpdate.

        List of parties associated to the current status/state value.  # noqa: E501

        :return: The related_party of this ContextUpdate.
        :rtype: List[RelatedPartyRefOrPartyRoleRef]
        """
        return self._related_party

    @related_party.setter
    def related_party(self, related_party: List[RelatedPartyRefOrPartyRoleRef]):
        """Sets the related_party of this ContextUpdate.

        List of parties associated to the current status/state value.  # noqa: E501

        :param related_party: The related_party of this ContextUpdate.
        :type related_party: List[RelatedPartyRefOrPartyRoleRef]
        """

        self._related_party = related_party
