from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.calendar_period import CalendarPeriod
from openapi_server.models.contact_medium import ContactMedium
from openapi_server.models.external_identifier import ExternalIdentifier
from openapi_server.models.geographic_site import GeographicSite
from openapi_server.models.geographic_site_feature import GeographicSiteFeature
from openapi_server.models.geographic_site_ref import GeographicSiteRef
from openapi_server.models.geographic_site_relationship import GeographicSiteRelationship
from openapi_server.models.place_ref_or_value import PlaceRefOrValue
from openapi_server.models.related_party_ref_or_party_role_ref import RelatedPartyRefOrPartyRoleRef
from openapi_server import util

from openapi_server.models.calendar_period import CalendarPeriod  # noqa: E501
from openapi_server.models.contact_medium import ContactMedium  # noqa: E501
from openapi_server.models.external_identifier import ExternalIdentifier  # noqa: E501
from openapi_server.models.geographic_site import GeographicSite  # noqa: E501
from openapi_server.models.geographic_site_feature import GeographicSiteFeature  # noqa: E501
from openapi_server.models.geographic_site_ref import GeographicSiteRef  # noqa: E501
from openapi_server.models.geographic_site_relationship import GeographicSiteRelationship  # noqa: E501
from openapi_server.models.place_ref_or_value import PlaceRefOrValue  # noqa: E501
from openapi_server.models.related_party_ref_or_party_role_ref import RelatedPartyRefOrPartyRoleRef  # noqa: E501

class GeographicSiteRefOrValue(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, base_type=None, schema_location=None, href=None, id=None, external_identifier=None, code=None, creation_date=None, description=None, status=None, related_party=None, calendar=None, place=None, site_relationship=None, site_category=None, contact_medium=None, site_feature=None, name=None, referred_type=None):  # noqa: E501
        """GeographicSiteRefOrValue - a model defined in OpenAPI

        :param type: The type of this GeographicSiteRefOrValue.  # noqa: E501
        :type type: str
        :param base_type: The base_type of this GeographicSiteRefOrValue.  # noqa: E501
        :type base_type: str
        :param schema_location: The schema_location of this GeographicSiteRefOrValue.  # noqa: E501
        :type schema_location: str
        :param href: The href of this GeographicSiteRefOrValue.  # noqa: E501
        :type href: str
        :param id: The id of this GeographicSiteRefOrValue.  # noqa: E501
        :type id: str
        :param external_identifier: The external_identifier of this GeographicSiteRefOrValue.  # noqa: E501
        :type external_identifier: List[ExternalIdentifier]
        :param code: The code of this GeographicSiteRefOrValue.  # noqa: E501
        :type code: str
        :param creation_date: The creation_date of this GeographicSiteRefOrValue.  # noqa: E501
        :type creation_date: datetime
        :param description: The description of this GeographicSiteRefOrValue.  # noqa: E501
        :type description: str
        :param status: The status of this GeographicSiteRefOrValue.  # noqa: E501
        :type status: str
        :param related_party: The related_party of this GeographicSiteRefOrValue.  # noqa: E501
        :type related_party: List[RelatedPartyRefOrPartyRoleRef]
        :param calendar: The calendar of this GeographicSiteRefOrValue.  # noqa: E501
        :type calendar: List[CalendarPeriod]
        :param place: The place of this GeographicSiteRefOrValue.  # noqa: E501
        :type place: List[PlaceRefOrValue]
        :param site_relationship: The site_relationship of this GeographicSiteRefOrValue.  # noqa: E501
        :type site_relationship: List[GeographicSiteRelationship]
        :param site_category: The site_category of this GeographicSiteRefOrValue.  # noqa: E501
        :type site_category: str
        :param contact_medium: The contact_medium of this GeographicSiteRefOrValue.  # noqa: E501
        :type contact_medium: List[ContactMedium]
        :param site_feature: The site_feature of this GeographicSiteRefOrValue.  # noqa: E501
        :type site_feature: List[GeographicSiteFeature]
        :param name: The name of this GeographicSiteRefOrValue.  # noqa: E501
        :type name: str
        :param referred_type: The referred_type of this GeographicSiteRefOrValue.  # noqa: E501
        :type referred_type: str
        """
        self.openapi_types = {
            'type': str,
            'base_type': str,
            'schema_location': str,
            'href': str,
            'id': str,
            'external_identifier': List[ExternalIdentifier],
            'code': str,
            'creation_date': datetime,
            'description': str,
            'status': str,
            'related_party': List[RelatedPartyRefOrPartyRoleRef],
            'calendar': List[CalendarPeriod],
            'place': List[PlaceRefOrValue],
            'site_relationship': List[GeographicSiteRelationship],
            'site_category': str,
            'contact_medium': List[ContactMedium],
            'site_feature': List[GeographicSiteFeature],
            'name': str,
            'referred_type': str
        }

        self.attribute_map = {
            'type': '@type',
            'base_type': '@baseType',
            'schema_location': '@schemaLocation',
            'href': 'href',
            'id': 'id',
            'external_identifier': 'externalIdentifier',
            'code': 'code',
            'creation_date': 'creationDate',
            'description': 'description',
            'status': 'status',
            'related_party': 'relatedParty',
            'calendar': 'calendar',
            'place': 'place',
            'site_relationship': 'siteRelationship',
            'site_category': 'siteCategory',
            'contact_medium': 'contactMedium',
            'site_feature': 'siteFeature',
            'name': 'name',
            'referred_type': '@referredType'
        }

        self._type = type
        self._base_type = base_type
        self._schema_location = schema_location
        self._href = href
        self._id = id
        self._external_identifier = external_identifier
        self._code = code
        self._creation_date = creation_date
        self._description = description
        self._status = status
        self._related_party = related_party
        self._calendar = calendar
        self._place = place
        self._site_relationship = site_relationship
        self._site_category = site_category
        self._contact_medium = contact_medium
        self._site_feature = site_feature
        self._name = name
        self._referred_type = referred_type

    @classmethod
    def from_dict(cls, dikt) -> 'GeographicSiteRefOrValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GeographicSiteRefOrValue of this GeographicSiteRefOrValue.  # noqa: E501
        :rtype: GeographicSiteRefOrValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this GeographicSiteRefOrValue.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :return: The type of this GeographicSiteRefOrValue.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this GeographicSiteRefOrValue.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :param type: The type of this GeographicSiteRefOrValue.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def base_type(self) -> str:
        """Gets the base_type of this GeographicSiteRefOrValue.

        When sub-classing, this defines the super-class  # noqa: E501

        :return: The base_type of this GeographicSiteRefOrValue.
        :rtype: str
        """
        return self._base_type

    @base_type.setter
    def base_type(self, base_type: str):
        """Sets the base_type of this GeographicSiteRefOrValue.

        When sub-classing, this defines the super-class  # noqa: E501

        :param base_type: The base_type of this GeographicSiteRefOrValue.
        :type base_type: str
        """

        self._base_type = base_type

    @property
    def schema_location(self) -> str:
        """Gets the schema_location of this GeographicSiteRefOrValue.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :return: The schema_location of this GeographicSiteRefOrValue.
        :rtype: str
        """
        return self._schema_location

    @schema_location.setter
    def schema_location(self, schema_location: str):
        """Sets the schema_location of this GeographicSiteRefOrValue.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :param schema_location: The schema_location of this GeographicSiteRefOrValue.
        :type schema_location: str
        """

        self._schema_location = schema_location

    @property
    def href(self) -> str:
        """Gets the href of this GeographicSiteRefOrValue.

        The URI of the referred entity.  # noqa: E501

        :return: The href of this GeographicSiteRefOrValue.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this GeographicSiteRefOrValue.

        The URI of the referred entity.  # noqa: E501

        :param href: The href of this GeographicSiteRefOrValue.
        :type href: str
        """

        self._href = href

    @property
    def id(self) -> str:
        """Gets the id of this GeographicSiteRefOrValue.

        The identifier of the referred entity.  # noqa: E501

        :return: The id of this GeographicSiteRefOrValue.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this GeographicSiteRefOrValue.

        The identifier of the referred entity.  # noqa: E501

        :param id: The id of this GeographicSiteRefOrValue.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def external_identifier(self) -> List[ExternalIdentifier]:
        """Gets the external_identifier of this GeographicSiteRefOrValue.

        Collection of external identifiers  # noqa: E501

        :return: The external_identifier of this GeographicSiteRefOrValue.
        :rtype: List[ExternalIdentifier]
        """
        return self._external_identifier

    @external_identifier.setter
    def external_identifier(self, external_identifier: List[ExternalIdentifier]):
        """Sets the external_identifier of this GeographicSiteRefOrValue.

        Collection of external identifiers  # noqa: E501

        :param external_identifier: The external_identifier of this GeographicSiteRefOrValue.
        :type external_identifier: List[ExternalIdentifier]
        """

        self._external_identifier = external_identifier

    @property
    def code(self) -> str:
        """Gets the code of this GeographicSiteRefOrValue.

        A code that may be used for some addressing schemes eg: [ANSI T1.253-1999]  # noqa: E501

        :return: The code of this GeographicSiteRefOrValue.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this GeographicSiteRefOrValue.

        A code that may be used for some addressing schemes eg: [ANSI T1.253-1999]  # noqa: E501

        :param code: The code of this GeographicSiteRefOrValue.
        :type code: str
        """

        self._code = code

    @property
    def creation_date(self) -> datetime:
        """Gets the creation_date of this GeographicSiteRefOrValue.

        Date and time when the GeographicSite was created  # noqa: E501

        :return: The creation_date of this GeographicSiteRefOrValue.
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date: datetime):
        """Sets the creation_date of this GeographicSiteRefOrValue.

        Date and time when the GeographicSite was created  # noqa: E501

        :param creation_date: The creation_date of this GeographicSiteRefOrValue.
        :type creation_date: datetime
        """

        self._creation_date = creation_date

    @property
    def description(self) -> str:
        """Gets the description of this GeographicSiteRefOrValue.

        Text describing additional information regarding the site  # noqa: E501

        :return: The description of this GeographicSiteRefOrValue.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this GeographicSiteRefOrValue.

        Text describing additional information regarding the site  # noqa: E501

        :param description: The description of this GeographicSiteRefOrValue.
        :type description: str
        """

        self._description = description

    @property
    def status(self) -> str:
        """Gets the status of this GeographicSiteRefOrValue.

        The condition of the GeographicSite, such as planned, underConstruction, cancelled, active, inactive, former  # noqa: E501

        :return: The status of this GeographicSiteRefOrValue.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this GeographicSiteRefOrValue.

        The condition of the GeographicSite, such as planned, underConstruction, cancelled, active, inactive, former  # noqa: E501

        :param status: The status of this GeographicSiteRefOrValue.
        :type status: str
        """

        self._status = status

    @property
    def related_party(self) -> List[RelatedPartyRefOrPartyRoleRef]:
        """Gets the related_party of this GeographicSiteRefOrValue.

        Related parties collection  # noqa: E501

        :return: The related_party of this GeographicSiteRefOrValue.
        :rtype: List[RelatedPartyRefOrPartyRoleRef]
        """
        return self._related_party

    @related_party.setter
    def related_party(self, related_party: List[RelatedPartyRefOrPartyRoleRef]):
        """Sets the related_party of this GeographicSiteRefOrValue.

        Related parties collection  # noqa: E501

        :param related_party: The related_party of this GeographicSiteRefOrValue.
        :type related_party: List[RelatedPartyRefOrPartyRoleRef]
        """

        self._related_party = related_party

    @property
    def calendar(self) -> List[CalendarPeriod]:
        """Gets the calendar of this GeographicSiteRefOrValue.

        Collection of calendar items  # noqa: E501

        :return: The calendar of this GeographicSiteRefOrValue.
        :rtype: List[CalendarPeriod]
        """
        return self._calendar

    @calendar.setter
    def calendar(self, calendar: List[CalendarPeriod]):
        """Sets the calendar of this GeographicSiteRefOrValue.

        Collection of calendar items  # noqa: E501

        :param calendar: The calendar of this GeographicSiteRefOrValue.
        :type calendar: List[CalendarPeriod]
        """

        self._calendar = calendar

    @property
    def place(self) -> List[PlaceRefOrValue]:
        """Gets the place of this GeographicSiteRefOrValue.

        Collection of place objects  # noqa: E501

        :return: The place of this GeographicSiteRefOrValue.
        :rtype: List[PlaceRefOrValue]
        """
        return self._place

    @place.setter
    def place(self, place: List[PlaceRefOrValue]):
        """Sets the place of this GeographicSiteRefOrValue.

        Collection of place objects  # noqa: E501

        :param place: The place of this GeographicSiteRefOrValue.
        :type place: List[PlaceRefOrValue]
        """

        self._place = place

    @property
    def site_relationship(self) -> List[GeographicSiteRelationship]:
        """Gets the site_relationship of this GeographicSiteRefOrValue.

        Collection of site siteRelationships  # noqa: E501

        :return: The site_relationship of this GeographicSiteRefOrValue.
        :rtype: List[GeographicSiteRelationship]
        """
        return self._site_relationship

    @site_relationship.setter
    def site_relationship(self, site_relationship: List[GeographicSiteRelationship]):
        """Sets the site_relationship of this GeographicSiteRefOrValue.

        Collection of site siteRelationships  # noqa: E501

        :param site_relationship: The site_relationship of this GeographicSiteRefOrValue.
        :type site_relationship: List[GeographicSiteRelationship]
        """

        self._site_relationship = site_relationship

    @property
    def site_category(self) -> str:
        """Gets the site_category of this GeographicSiteRefOrValue.

        Site classification/category.  # noqa: E501

        :return: The site_category of this GeographicSiteRefOrValue.
        :rtype: str
        """
        return self._site_category

    @site_category.setter
    def site_category(self, site_category: str):
        """Sets the site_category of this GeographicSiteRefOrValue.

        Site classification/category.  # noqa: E501

        :param site_category: The site_category of this GeographicSiteRefOrValue.
        :type site_category: str
        """

        self._site_category = site_category

    @property
    def contact_medium(self) -> List[ContactMedium]:
        """Gets the contact_medium of this GeographicSiteRefOrValue.

        Collection of contact information  # noqa: E501

        :return: The contact_medium of this GeographicSiteRefOrValue.
        :rtype: List[ContactMedium]
        """
        return self._contact_medium

    @contact_medium.setter
    def contact_medium(self, contact_medium: List[ContactMedium]):
        """Sets the contact_medium of this GeographicSiteRefOrValue.

        Collection of contact information  # noqa: E501

        :param contact_medium: The contact_medium of this GeographicSiteRefOrValue.
        :type contact_medium: List[ContactMedium]
        """

        self._contact_medium = contact_medium

    @property
    def site_feature(self) -> List[GeographicSiteFeature]:
        """Gets the site_feature of this GeographicSiteRefOrValue.

        Collection of site features  # noqa: E501

        :return: The site_feature of this GeographicSiteRefOrValue.
        :rtype: List[GeographicSiteFeature]
        """
        return self._site_feature

    @site_feature.setter
    def site_feature(self, site_feature: List[GeographicSiteFeature]):
        """Sets the site_feature of this GeographicSiteRefOrValue.

        Collection of site features  # noqa: E501

        :param site_feature: The site_feature of this GeographicSiteRefOrValue.
        :type site_feature: List[GeographicSiteFeature]
        """

        self._site_feature = site_feature

    @property
    def name(self) -> str:
        """Gets the name of this GeographicSiteRefOrValue.

        Name of the referred entity.  # noqa: E501

        :return: The name of this GeographicSiteRefOrValue.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this GeographicSiteRefOrValue.

        Name of the referred entity.  # noqa: E501

        :param name: The name of this GeographicSiteRefOrValue.
        :type name: str
        """

        self._name = name

    @property
    def referred_type(self) -> str:
        """Gets the referred_type of this GeographicSiteRefOrValue.

        The actual type of the target instance when needed for disambiguation.  # noqa: E501

        :return: The referred_type of this GeographicSiteRefOrValue.
        :rtype: str
        """
        return self._referred_type

    @referred_type.setter
    def referred_type(self, referred_type: str):
        """Sets the referred_type of this GeographicSiteRefOrValue.

        The actual type of the target instance when needed for disambiguation.  # noqa: E501

        :param referred_type: The referred_type of this GeographicSiteRefOrValue.
        :type referred_type: str
        """

        self._referred_type = referred_type
