from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.external_identifier import ExternalIdentifier
from openapi_server.models.geographic_location import GeographicLocation
from openapi_server.models.geographic_location_ref import GeographicLocationRef
from openapi_server import util

from openapi_server.models.external_identifier import ExternalIdentifier  # noqa: E501
from openapi_server.models.geographic_location import GeographicLocation  # noqa: E501
from openapi_server.models.geographic_location_ref import GeographicLocationRef  # noqa: E501

class GeographicLocationRefOrValue(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, base_type=None, schema_location=None, href=None, id=None, external_identifier=None, bbox=None, name=None, referred_type=None):  # noqa: E501
        """GeographicLocationRefOrValue - a model defined in OpenAPI

        :param type: The type of this GeographicLocationRefOrValue.  # noqa: E501
        :type type: str
        :param base_type: The base_type of this GeographicLocationRefOrValue.  # noqa: E501
        :type base_type: str
        :param schema_location: The schema_location of this GeographicLocationRefOrValue.  # noqa: E501
        :type schema_location: str
        :param href: The href of this GeographicLocationRefOrValue.  # noqa: E501
        :type href: str
        :param id: The id of this GeographicLocationRefOrValue.  # noqa: E501
        :type id: str
        :param external_identifier: The external_identifier of this GeographicLocationRefOrValue.  # noqa: E501
        :type external_identifier: List[ExternalIdentifier]
        :param bbox: The bbox of this GeographicLocationRefOrValue.  # noqa: E501
        :type bbox: List[float]
        :param name: The name of this GeographicLocationRefOrValue.  # noqa: E501
        :type name: str
        :param referred_type: The referred_type of this GeographicLocationRefOrValue.  # noqa: E501
        :type referred_type: str
        """
        self.openapi_types = {
            'type': str,
            'base_type': str,
            'schema_location': str,
            'href': str,
            'id': str,
            'external_identifier': List[ExternalIdentifier],
            'bbox': List[float],
            'name': str,
            'referred_type': str
        }

        self.attribute_map = {
            'type': '@type',
            'base_type': '@baseType',
            'schema_location': '@schemaLocation',
            'href': 'href',
            'id': 'id',
            'external_identifier': 'externalIdentifier',
            'bbox': 'bbox',
            'name': 'name',
            'referred_type': '@referredType'
        }

        self._type = type
        self._base_type = base_type
        self._schema_location = schema_location
        self._href = href
        self._id = id
        self._external_identifier = external_identifier
        self._bbox = bbox
        self._name = name
        self._referred_type = referred_type

    @classmethod
    def from_dict(cls, dikt) -> 'GeographicLocationRefOrValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GeographicLocationRefOrValue of this GeographicLocationRefOrValue.  # noqa: E501
        :rtype: GeographicLocationRefOrValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this GeographicLocationRefOrValue.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :return: The type of this GeographicLocationRefOrValue.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this GeographicLocationRefOrValue.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :param type: The type of this GeographicLocationRefOrValue.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def base_type(self) -> str:
        """Gets the base_type of this GeographicLocationRefOrValue.

        When sub-classing, this defines the super-class  # noqa: E501

        :return: The base_type of this GeographicLocationRefOrValue.
        :rtype: str
        """
        return self._base_type

    @base_type.setter
    def base_type(self, base_type: str):
        """Sets the base_type of this GeographicLocationRefOrValue.

        When sub-classing, this defines the super-class  # noqa: E501

        :param base_type: The base_type of this GeographicLocationRefOrValue.
        :type base_type: str
        """

        self._base_type = base_type

    @property
    def schema_location(self) -> str:
        """Gets the schema_location of this GeographicLocationRefOrValue.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :return: The schema_location of this GeographicLocationRefOrValue.
        :rtype: str
        """
        return self._schema_location

    @schema_location.setter
    def schema_location(self, schema_location: str):
        """Sets the schema_location of this GeographicLocationRefOrValue.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :param schema_location: The schema_location of this GeographicLocationRefOrValue.
        :type schema_location: str
        """

        self._schema_location = schema_location

    @property
    def href(self) -> str:
        """Gets the href of this GeographicLocationRefOrValue.

        The URI of the referred entity.  # noqa: E501

        :return: The href of this GeographicLocationRefOrValue.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this GeographicLocationRefOrValue.

        The URI of the referred entity.  # noqa: E501

        :param href: The href of this GeographicLocationRefOrValue.
        :type href: str
        """

        self._href = href

    @property
    def id(self) -> str:
        """Gets the id of this GeographicLocationRefOrValue.

        The identifier of the referred entity.  # noqa: E501

        :return: The id of this GeographicLocationRefOrValue.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this GeographicLocationRefOrValue.

        The identifier of the referred entity.  # noqa: E501

        :param id: The id of this GeographicLocationRefOrValue.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def external_identifier(self) -> List[ExternalIdentifier]:
        """Gets the external_identifier of this GeographicLocationRefOrValue.

        Collection of external identifiers  # noqa: E501

        :return: The external_identifier of this GeographicLocationRefOrValue.
        :rtype: List[ExternalIdentifier]
        """
        return self._external_identifier

    @external_identifier.setter
    def external_identifier(self, external_identifier: List[ExternalIdentifier]):
        """Sets the external_identifier of this GeographicLocationRefOrValue.

        Collection of external identifiers  # noqa: E501

        :param external_identifier: The external_identifier of this GeographicLocationRefOrValue.
        :type external_identifier: List[ExternalIdentifier]
        """

        self._external_identifier = external_identifier

    @property
    def bbox(self) -> List[float]:
        """Gets the bbox of this GeographicLocationRefOrValue.

        A bounding box array that contains the geometry. The axes order follows the axes order of the geometry  # noqa: E501

        :return: The bbox of this GeographicLocationRefOrValue.
        :rtype: List[float]
        """
        return self._bbox

    @bbox.setter
    def bbox(self, bbox: List[float]):
        """Sets the bbox of this GeographicLocationRefOrValue.

        A bounding box array that contains the geometry. The axes order follows the axes order of the geometry  # noqa: E501

        :param bbox: The bbox of this GeographicLocationRefOrValue.
        :type bbox: List[float]
        """
        if bbox is not None and len(bbox) < 4:
            raise ValueError("Invalid value for `bbox`, number of items must be greater than or equal to `4`")  # noqa: E501

        self._bbox = bbox

    @property
    def name(self) -> str:
        """Gets the name of this GeographicLocationRefOrValue.

        Name of the referred entity.  # noqa: E501

        :return: The name of this GeographicLocationRefOrValue.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this GeographicLocationRefOrValue.

        Name of the referred entity.  # noqa: E501

        :param name: The name of this GeographicLocationRefOrValue.
        :type name: str
        """

        self._name = name

    @property
    def referred_type(self) -> str:
        """Gets the referred_type of this GeographicLocationRefOrValue.

        The actual type of the target instance when needed for disambiguation.  # noqa: E501

        :return: The referred_type of this GeographicLocationRefOrValue.
        :rtype: str
        """
        return self._referred_type

    @referred_type.setter
    def referred_type(self, referred_type: str):
        """Sets the referred_type of this GeographicLocationRefOrValue.

        The actual type of the target instance when needed for disambiguation.  # noqa: E501

        :param referred_type: The referred_type of this GeographicLocationRefOrValue.
        :type referred_type: str
        """

        self._referred_type = referred_type
