from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.calendar_period import CalendarPeriod
from openapi_server.models.contact_medium import ContactMedium
from openapi_server.models.external_identifier import ExternalIdentifier
from openapi_server.models.geographic_address import GeographicAddress
from openapi_server.models.geographic_address_relationship import GeographicAddressRelationship
from openapi_server.models.geographic_location import GeographicLocation
from openapi_server.models.geographic_location_ref_or_value import GeographicLocationRefOrValue
from openapi_server.models.geographic_site import GeographicSite
from openapi_server.models.geographic_site_feature import GeographicSiteFeature
from openapi_server.models.geographic_site_ref_or_value import GeographicSiteRefOrValue
from openapi_server.models.geographic_site_relationship import GeographicSiteRelationship
from openapi_server.models.geographic_sub_address import GeographicSubAddress
from openapi_server.models.place_ref import PlaceRef
from openapi_server.models.related_party_ref_or_party_role_ref import RelatedPartyRefOrPartyRoleRef
from openapi_server.models.standard_identifier import StandardIdentifier
from openapi_server import util

from openapi_server.models.calendar_period import CalendarPeriod  # noqa: E501
from openapi_server.models.contact_medium import ContactMedium  # noqa: E501
from openapi_server.models.external_identifier import ExternalIdentifier  # noqa: E501
from openapi_server.models.geographic_address import GeographicAddress  # noqa: E501
from openapi_server.models.geographic_address_relationship import GeographicAddressRelationship  # noqa: E501
from openapi_server.models.geographic_location import GeographicLocation  # noqa: E501
from openapi_server.models.geographic_location_ref_or_value import GeographicLocationRefOrValue  # noqa: E501
from openapi_server.models.geographic_site import GeographicSite  # noqa: E501
from openapi_server.models.geographic_site_feature import GeographicSiteFeature  # noqa: E501
from openapi_server.models.geographic_site_ref_or_value import GeographicSiteRefOrValue  # noqa: E501
from openapi_server.models.geographic_site_relationship import GeographicSiteRelationship  # noqa: E501
from openapi_server.models.geographic_sub_address import GeographicSubAddress  # noqa: E501
from openapi_server.models.place_ref import PlaceRef  # noqa: E501
from openapi_server.models.related_party_ref_or_party_role_ref import RelatedPartyRefOrPartyRoleRef  # noqa: E501
from openapi_server.models.standard_identifier import StandardIdentifier  # noqa: E501

class PlaceRefOrValue(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, base_type=None, schema_location=None, href=None, id=None, external_identifier=None, bbox=None, code=None, creation_date=None, description=None, status=None, related_party=None, calendar=None, place=None, site_relationship=None, site_category=None, contact_medium=None, site_feature=None, city=None, country=None, locality=None, postcode=None, state_or_province=None, street_name=None, street_nr=None, street_nr_last=None, street_nr_last_suffix=None, street_nr_suffix=None, street_suffix=None, street_type=None, country_code=None, geographic_location=None, geographic_sub_address=None, geographic_address_type=None, geographic_site=None, geographic_address_relationship=None, name=None, referred_type=None):  # noqa: E501
        """PlaceRefOrValue - a model defined in OpenAPI

        :param type: The type of this PlaceRefOrValue.  # noqa: E501
        :type type: str
        :param base_type: The base_type of this PlaceRefOrValue.  # noqa: E501
        :type base_type: str
        :param schema_location: The schema_location of this PlaceRefOrValue.  # noqa: E501
        :type schema_location: str
        :param href: The href of this PlaceRefOrValue.  # noqa: E501
        :type href: str
        :param id: The id of this PlaceRefOrValue.  # noqa: E501
        :type id: str
        :param external_identifier: The external_identifier of this PlaceRefOrValue.  # noqa: E501
        :type external_identifier: List[ExternalIdentifier]
        :param bbox: The bbox of this PlaceRefOrValue.  # noqa: E501
        :type bbox: List[float]
        :param code: The code of this PlaceRefOrValue.  # noqa: E501
        :type code: str
        :param creation_date: The creation_date of this PlaceRefOrValue.  # noqa: E501
        :type creation_date: datetime
        :param description: The description of this PlaceRefOrValue.  # noqa: E501
        :type description: str
        :param status: The status of this PlaceRefOrValue.  # noqa: E501
        :type status: str
        :param related_party: The related_party of this PlaceRefOrValue.  # noqa: E501
        :type related_party: List[RelatedPartyRefOrPartyRoleRef]
        :param calendar: The calendar of this PlaceRefOrValue.  # noqa: E501
        :type calendar: List[CalendarPeriod]
        :param place: The place of this PlaceRefOrValue.  # noqa: E501
        :type place: List[PlaceRefOrValue]
        :param site_relationship: The site_relationship of this PlaceRefOrValue.  # noqa: E501
        :type site_relationship: List[GeographicSiteRelationship]
        :param site_category: The site_category of this PlaceRefOrValue.  # noqa: E501
        :type site_category: str
        :param contact_medium: The contact_medium of this PlaceRefOrValue.  # noqa: E501
        :type contact_medium: List[ContactMedium]
        :param site_feature: The site_feature of this PlaceRefOrValue.  # noqa: E501
        :type site_feature: List[GeographicSiteFeature]
        :param city: The city of this PlaceRefOrValue.  # noqa: E501
        :type city: str
        :param country: The country of this PlaceRefOrValue.  # noqa: E501
        :type country: str
        :param locality: The locality of this PlaceRefOrValue.  # noqa: E501
        :type locality: str
        :param postcode: The postcode of this PlaceRefOrValue.  # noqa: E501
        :type postcode: str
        :param state_or_province: The state_or_province of this PlaceRefOrValue.  # noqa: E501
        :type state_or_province: str
        :param street_name: The street_name of this PlaceRefOrValue.  # noqa: E501
        :type street_name: str
        :param street_nr: The street_nr of this PlaceRefOrValue.  # noqa: E501
        :type street_nr: str
        :param street_nr_last: The street_nr_last of this PlaceRefOrValue.  # noqa: E501
        :type street_nr_last: str
        :param street_nr_last_suffix: The street_nr_last_suffix of this PlaceRefOrValue.  # noqa: E501
        :type street_nr_last_suffix: str
        :param street_nr_suffix: The street_nr_suffix of this PlaceRefOrValue.  # noqa: E501
        :type street_nr_suffix: str
        :param street_suffix: The street_suffix of this PlaceRefOrValue.  # noqa: E501
        :type street_suffix: str
        :param street_type: The street_type of this PlaceRefOrValue.  # noqa: E501
        :type street_type: str
        :param country_code: The country_code of this PlaceRefOrValue.  # noqa: E501
        :type country_code: List[StandardIdentifier]
        :param geographic_location: The geographic_location of this PlaceRefOrValue.  # noqa: E501
        :type geographic_location: GeographicLocationRefOrValue
        :param geographic_sub_address: The geographic_sub_address of this PlaceRefOrValue.  # noqa: E501
        :type geographic_sub_address: List[GeographicSubAddress]
        :param geographic_address_type: The geographic_address_type of this PlaceRefOrValue.  # noqa: E501
        :type geographic_address_type: str
        :param geographic_site: The geographic_site of this PlaceRefOrValue.  # noqa: E501
        :type geographic_site: GeographicSiteRefOrValue
        :param geographic_address_relationship: The geographic_address_relationship of this PlaceRefOrValue.  # noqa: E501
        :type geographic_address_relationship: List[GeographicAddressRelationship]
        :param name: The name of this PlaceRefOrValue.  # noqa: E501
        :type name: str
        :param referred_type: The referred_type of this PlaceRefOrValue.  # noqa: E501
        :type referred_type: str
        """
        self.openapi_types = {
            'type': str,
            'base_type': str,
            'schema_location': str,
            'href': str,
            'id': str,
            'external_identifier': List[ExternalIdentifier],
            'bbox': List[float],
            'code': str,
            'creation_date': datetime,
            'description': str,
            'status': str,
            'related_party': List[RelatedPartyRefOrPartyRoleRef],
            'calendar': List[CalendarPeriod],
            'place': List[PlaceRefOrValue],
            'site_relationship': List[GeographicSiteRelationship],
            'site_category': str,
            'contact_medium': List[ContactMedium],
            'site_feature': List[GeographicSiteFeature],
            'city': str,
            'country': str,
            'locality': str,
            'postcode': str,
            'state_or_province': str,
            'street_name': str,
            'street_nr': str,
            'street_nr_last': str,
            'street_nr_last_suffix': str,
            'street_nr_suffix': str,
            'street_suffix': str,
            'street_type': str,
            'country_code': List[StandardIdentifier],
            'geographic_location': GeographicLocationRefOrValue,
            'geographic_sub_address': List[GeographicSubAddress],
            'geographic_address_type': str,
            'geographic_site': GeographicSiteRefOrValue,
            'geographic_address_relationship': List[GeographicAddressRelationship],
            'name': str,
            'referred_type': str
        }

        self.attribute_map = {
            'type': '@type',
            'base_type': '@baseType',
            'schema_location': '@schemaLocation',
            'href': 'href',
            'id': 'id',
            'external_identifier': 'externalIdentifier',
            'bbox': 'bbox',
            'code': 'code',
            'creation_date': 'creationDate',
            'description': 'description',
            'status': 'status',
            'related_party': 'relatedParty',
            'calendar': 'calendar',
            'place': 'place',
            'site_relationship': 'siteRelationship',
            'site_category': 'siteCategory',
            'contact_medium': 'contactMedium',
            'site_feature': 'siteFeature',
            'city': 'city',
            'country': 'country',
            'locality': 'locality',
            'postcode': 'postcode',
            'state_or_province': 'stateOrProvince',
            'street_name': 'streetName',
            'street_nr': 'streetNr',
            'street_nr_last': 'streetNrLast',
            'street_nr_last_suffix': 'streetNrLastSuffix',
            'street_nr_suffix': 'streetNrSuffix',
            'street_suffix': 'streetSuffix',
            'street_type': 'streetType',
            'country_code': 'countryCode',
            'geographic_location': 'geographicLocation',
            'geographic_sub_address': 'geographicSubAddress',
            'geographic_address_type': 'geographicAddressType',
            'geographic_site': 'geographicSite',
            'geographic_address_relationship': 'geographicAddressRelationship',
            'name': 'name',
            'referred_type': '@referredType'
        }

        self._type = type
        self._base_type = base_type
        self._schema_location = schema_location
        self._href = href
        self._id = id
        self._external_identifier = external_identifier
        self._bbox = bbox
        self._code = code
        self._creation_date = creation_date
        self._description = description
        self._status = status
        self._related_party = related_party
        self._calendar = calendar
        self._place = place
        self._site_relationship = site_relationship
        self._site_category = site_category
        self._contact_medium = contact_medium
        self._site_feature = site_feature
        self._city = city
        self._country = country
        self._locality = locality
        self._postcode = postcode
        self._state_or_province = state_or_province
        self._street_name = street_name
        self._street_nr = street_nr
        self._street_nr_last = street_nr_last
        self._street_nr_last_suffix = street_nr_last_suffix
        self._street_nr_suffix = street_nr_suffix
        self._street_suffix = street_suffix
        self._street_type = street_type
        self._country_code = country_code
        self._geographic_location = geographic_location
        self._geographic_sub_address = geographic_sub_address
        self._geographic_address_type = geographic_address_type
        self._geographic_site = geographic_site
        self._geographic_address_relationship = geographic_address_relationship
        self._name = name
        self._referred_type = referred_type

    @classmethod
    def from_dict(cls, dikt) -> 'PlaceRefOrValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlaceRefOrValue of this PlaceRefOrValue.  # noqa: E501
        :rtype: PlaceRefOrValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this PlaceRefOrValue.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :return: The type of this PlaceRefOrValue.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this PlaceRefOrValue.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :param type: The type of this PlaceRefOrValue.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def base_type(self) -> str:
        """Gets the base_type of this PlaceRefOrValue.

        When sub-classing, this defines the super-class  # noqa: E501

        :return: The base_type of this PlaceRefOrValue.
        :rtype: str
        """
        return self._base_type

    @base_type.setter
    def base_type(self, base_type: str):
        """Sets the base_type of this PlaceRefOrValue.

        When sub-classing, this defines the super-class  # noqa: E501

        :param base_type: The base_type of this PlaceRefOrValue.
        :type base_type: str
        """

        self._base_type = base_type

    @property
    def schema_location(self) -> str:
        """Gets the schema_location of this PlaceRefOrValue.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :return: The schema_location of this PlaceRefOrValue.
        :rtype: str
        """
        return self._schema_location

    @schema_location.setter
    def schema_location(self, schema_location: str):
        """Sets the schema_location of this PlaceRefOrValue.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :param schema_location: The schema_location of this PlaceRefOrValue.
        :type schema_location: str
        """

        self._schema_location = schema_location

    @property
    def href(self) -> str:
        """Gets the href of this PlaceRefOrValue.

        The URI of the referred entity.  # noqa: E501

        :return: The href of this PlaceRefOrValue.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this PlaceRefOrValue.

        The URI of the referred entity.  # noqa: E501

        :param href: The href of this PlaceRefOrValue.
        :type href: str
        """

        self._href = href

    @property
    def id(self) -> str:
        """Gets the id of this PlaceRefOrValue.

        The identifier of the referred entity.  # noqa: E501

        :return: The id of this PlaceRefOrValue.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this PlaceRefOrValue.

        The identifier of the referred entity.  # noqa: E501

        :param id: The id of this PlaceRefOrValue.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def external_identifier(self) -> List[ExternalIdentifier]:
        """Gets the external_identifier of this PlaceRefOrValue.

        Collection of external identifiers  # noqa: E501

        :return: The external_identifier of this PlaceRefOrValue.
        :rtype: List[ExternalIdentifier]
        """
        return self._external_identifier

    @external_identifier.setter
    def external_identifier(self, external_identifier: List[ExternalIdentifier]):
        """Sets the external_identifier of this PlaceRefOrValue.

        Collection of external identifiers  # noqa: E501

        :param external_identifier: The external_identifier of this PlaceRefOrValue.
        :type external_identifier: List[ExternalIdentifier]
        """

        self._external_identifier = external_identifier

    @property
    def bbox(self) -> List[float]:
        """Gets the bbox of this PlaceRefOrValue.

        A bounding box array that contains the geometry. The axes order follows the axes order of the geometry  # noqa: E501

        :return: The bbox of this PlaceRefOrValue.
        :rtype: List[float]
        """
        return self._bbox

    @bbox.setter
    def bbox(self, bbox: List[float]):
        """Sets the bbox of this PlaceRefOrValue.

        A bounding box array that contains the geometry. The axes order follows the axes order of the geometry  # noqa: E501

        :param bbox: The bbox of this PlaceRefOrValue.
        :type bbox: List[float]
        """
        if bbox is not None and len(bbox) < 4:
            raise ValueError("Invalid value for `bbox`, number of items must be greater than or equal to `4`")  # noqa: E501

        self._bbox = bbox

    @property
    def code(self) -> str:
        """Gets the code of this PlaceRefOrValue.

        A code that may be used for some addressing schemes eg: [ANSI T1.253-1999]  # noqa: E501

        :return: The code of this PlaceRefOrValue.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this PlaceRefOrValue.

        A code that may be used for some addressing schemes eg: [ANSI T1.253-1999]  # noqa: E501

        :param code: The code of this PlaceRefOrValue.
        :type code: str
        """

        self._code = code

    @property
    def creation_date(self) -> datetime:
        """Gets the creation_date of this PlaceRefOrValue.

        Date and time when the GeographicSite was created  # noqa: E501

        :return: The creation_date of this PlaceRefOrValue.
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date: datetime):
        """Sets the creation_date of this PlaceRefOrValue.

        Date and time when the GeographicSite was created  # noqa: E501

        :param creation_date: The creation_date of this PlaceRefOrValue.
        :type creation_date: datetime
        """

        self._creation_date = creation_date

    @property
    def description(self) -> str:
        """Gets the description of this PlaceRefOrValue.

        Text describing additional information regarding the site  # noqa: E501

        :return: The description of this PlaceRefOrValue.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this PlaceRefOrValue.

        Text describing additional information regarding the site  # noqa: E501

        :param description: The description of this PlaceRefOrValue.
        :type description: str
        """

        self._description = description

    @property
    def status(self) -> str:
        """Gets the status of this PlaceRefOrValue.

        The condition of the GeographicSite, such as planned, underConstruction, cancelled, active, inactive, former  # noqa: E501

        :return: The status of this PlaceRefOrValue.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this PlaceRefOrValue.

        The condition of the GeographicSite, such as planned, underConstruction, cancelled, active, inactive, former  # noqa: E501

        :param status: The status of this PlaceRefOrValue.
        :type status: str
        """

        self._status = status

    @property
    def related_party(self) -> List[RelatedPartyRefOrPartyRoleRef]:
        """Gets the related_party of this PlaceRefOrValue.

        Related parties collection  # noqa: E501

        :return: The related_party of this PlaceRefOrValue.
        :rtype: List[RelatedPartyRefOrPartyRoleRef]
        """
        return self._related_party

    @related_party.setter
    def related_party(self, related_party: List[RelatedPartyRefOrPartyRoleRef]):
        """Sets the related_party of this PlaceRefOrValue.

        Related parties collection  # noqa: E501

        :param related_party: The related_party of this PlaceRefOrValue.
        :type related_party: List[RelatedPartyRefOrPartyRoleRef]
        """

        self._related_party = related_party

    @property
    def calendar(self) -> List[CalendarPeriod]:
        """Gets the calendar of this PlaceRefOrValue.

        Collection of calendar items  # noqa: E501

        :return: The calendar of this PlaceRefOrValue.
        :rtype: List[CalendarPeriod]
        """
        return self._calendar

    @calendar.setter
    def calendar(self, calendar: List[CalendarPeriod]):
        """Sets the calendar of this PlaceRefOrValue.

        Collection of calendar items  # noqa: E501

        :param calendar: The calendar of this PlaceRefOrValue.
        :type calendar: List[CalendarPeriod]
        """

        self._calendar = calendar

    @property
    def place(self) -> List[PlaceRefOrValue]:
        """Gets the place of this PlaceRefOrValue.

        Collection of place objects  # noqa: E501

        :return: The place of this PlaceRefOrValue.
        :rtype: List[PlaceRefOrValue]
        """
        return self._place

    @place.setter
    def place(self, place: List[PlaceRefOrValue]):
        """Sets the place of this PlaceRefOrValue.

        Collection of place objects  # noqa: E501

        :param place: The place of this PlaceRefOrValue.
        :type place: List[PlaceRefOrValue]
        """

        self._place = place

    @property
    def site_relationship(self) -> List[GeographicSiteRelationship]:
        """Gets the site_relationship of this PlaceRefOrValue.

        Collection of site siteRelationships  # noqa: E501

        :return: The site_relationship of this PlaceRefOrValue.
        :rtype: List[GeographicSiteRelationship]
        """
        return self._site_relationship

    @site_relationship.setter
    def site_relationship(self, site_relationship: List[GeographicSiteRelationship]):
        """Sets the site_relationship of this PlaceRefOrValue.

        Collection of site siteRelationships  # noqa: E501

        :param site_relationship: The site_relationship of this PlaceRefOrValue.
        :type site_relationship: List[GeographicSiteRelationship]
        """

        self._site_relationship = site_relationship

    @property
    def site_category(self) -> str:
        """Gets the site_category of this PlaceRefOrValue.

        Site classification/category.  # noqa: E501

        :return: The site_category of this PlaceRefOrValue.
        :rtype: str
        """
        return self._site_category

    @site_category.setter
    def site_category(self, site_category: str):
        """Sets the site_category of this PlaceRefOrValue.

        Site classification/category.  # noqa: E501

        :param site_category: The site_category of this PlaceRefOrValue.
        :type site_category: str
        """

        self._site_category = site_category

    @property
    def contact_medium(self) -> List[ContactMedium]:
        """Gets the contact_medium of this PlaceRefOrValue.

        Collection of contact information  # noqa: E501

        :return: The contact_medium of this PlaceRefOrValue.
        :rtype: List[ContactMedium]
        """
        return self._contact_medium

    @contact_medium.setter
    def contact_medium(self, contact_medium: List[ContactMedium]):
        """Sets the contact_medium of this PlaceRefOrValue.

        Collection of contact information  # noqa: E501

        :param contact_medium: The contact_medium of this PlaceRefOrValue.
        :type contact_medium: List[ContactMedium]
        """

        self._contact_medium = contact_medium

    @property
    def site_feature(self) -> List[GeographicSiteFeature]:
        """Gets the site_feature of this PlaceRefOrValue.

        Collection of site features  # noqa: E501

        :return: The site_feature of this PlaceRefOrValue.
        :rtype: List[GeographicSiteFeature]
        """
        return self._site_feature

    @site_feature.setter
    def site_feature(self, site_feature: List[GeographicSiteFeature]):
        """Sets the site_feature of this PlaceRefOrValue.

        Collection of site features  # noqa: E501

        :param site_feature: The site_feature of this PlaceRefOrValue.
        :type site_feature: List[GeographicSiteFeature]
        """

        self._site_feature = site_feature

    @property
    def city(self) -> str:
        """Gets the city of this PlaceRefOrValue.

        City that the address is in  # noqa: E501

        :return: The city of this PlaceRefOrValue.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this PlaceRefOrValue.

        City that the address is in  # noqa: E501

        :param city: The city of this PlaceRefOrValue.
        :type city: str
        """

        self._city = city

    @property
    def country(self) -> str:
        """Gets the country of this PlaceRefOrValue.

        Country that the address is in  # noqa: E501

        :return: The country of this PlaceRefOrValue.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this PlaceRefOrValue.

        Country that the address is in  # noqa: E501

        :param country: The country of this PlaceRefOrValue.
        :type country: str
        """

        self._country = country

    @property
    def locality(self) -> str:
        """Gets the locality of this PlaceRefOrValue.

        An area of defined or undefined boundaries within a local authority or other legislatively defined area, usually rural or semi rural in nature. [ANZLIC-STREET], or a suburb, a bounded locality within a city, town or shire principally of urban character [ANZLICSTREET]  # noqa: E501

        :return: The locality of this PlaceRefOrValue.
        :rtype: str
        """
        return self._locality

    @locality.setter
    def locality(self, locality: str):
        """Sets the locality of this PlaceRefOrValue.

        An area of defined or undefined boundaries within a local authority or other legislatively defined area, usually rural or semi rural in nature. [ANZLIC-STREET], or a suburb, a bounded locality within a city, town or shire principally of urban character [ANZLICSTREET]  # noqa: E501

        :param locality: The locality of this PlaceRefOrValue.
        :type locality: str
        """

        self._locality = locality

    @property
    def postcode(self) -> str:
        """Gets the postcode of this PlaceRefOrValue.

        descriptor for a postal delivery area, used to speed and simplify the delivery of mail (also know as zipcode)  # noqa: E501

        :return: The postcode of this PlaceRefOrValue.
        :rtype: str
        """
        return self._postcode

    @postcode.setter
    def postcode(self, postcode: str):
        """Sets the postcode of this PlaceRefOrValue.

        descriptor for a postal delivery area, used to speed and simplify the delivery of mail (also know as zipcode)  # noqa: E501

        :param postcode: The postcode of this PlaceRefOrValue.
        :type postcode: str
        """

        self._postcode = postcode

    @property
    def state_or_province(self) -> str:
        """Gets the state_or_province of this PlaceRefOrValue.

        the State or Province that the address is in  # noqa: E501

        :return: The state_or_province of this PlaceRefOrValue.
        :rtype: str
        """
        return self._state_or_province

    @state_or_province.setter
    def state_or_province(self, state_or_province: str):
        """Sets the state_or_province of this PlaceRefOrValue.

        the State or Province that the address is in  # noqa: E501

        :param state_or_province: The state_or_province of this PlaceRefOrValue.
        :type state_or_province: str
        """

        self._state_or_province = state_or_province

    @property
    def street_name(self) -> str:
        """Gets the street_name of this PlaceRefOrValue.

        Name of the street or other street type  # noqa: E501

        :return: The street_name of this PlaceRefOrValue.
        :rtype: str
        """
        return self._street_name

    @street_name.setter
    def street_name(self, street_name: str):
        """Sets the street_name of this PlaceRefOrValue.

        Name of the street or other street type  # noqa: E501

        :param street_name: The street_name of this PlaceRefOrValue.
        :type street_name: str
        """

        self._street_name = street_name

    @property
    def street_nr(self) -> str:
        """Gets the street_nr of this PlaceRefOrValue.

        Number identifying a specific property on a public street. It may be combined with streetNrLast for ranged addresses  # noqa: E501

        :return: The street_nr of this PlaceRefOrValue.
        :rtype: str
        """
        return self._street_nr

    @street_nr.setter
    def street_nr(self, street_nr: str):
        """Sets the street_nr of this PlaceRefOrValue.

        Number identifying a specific property on a public street. It may be combined with streetNrLast for ranged addresses  # noqa: E501

        :param street_nr: The street_nr of this PlaceRefOrValue.
        :type street_nr: str
        """

        self._street_nr = street_nr

    @property
    def street_nr_last(self) -> str:
        """Gets the street_nr_last of this PlaceRefOrValue.

        Last number in a range of street numbers allocated to a property  # noqa: E501

        :return: The street_nr_last of this PlaceRefOrValue.
        :rtype: str
        """
        return self._street_nr_last

    @street_nr_last.setter
    def street_nr_last(self, street_nr_last: str):
        """Sets the street_nr_last of this PlaceRefOrValue.

        Last number in a range of street numbers allocated to a property  # noqa: E501

        :param street_nr_last: The street_nr_last of this PlaceRefOrValue.
        :type street_nr_last: str
        """

        self._street_nr_last = street_nr_last

    @property
    def street_nr_last_suffix(self) -> str:
        """Gets the street_nr_last_suffix of this PlaceRefOrValue.

        Last street number suffix for a ranged address  # noqa: E501

        :return: The street_nr_last_suffix of this PlaceRefOrValue.
        :rtype: str
        """
        return self._street_nr_last_suffix

    @street_nr_last_suffix.setter
    def street_nr_last_suffix(self, street_nr_last_suffix: str):
        """Sets the street_nr_last_suffix of this PlaceRefOrValue.

        Last street number suffix for a ranged address  # noqa: E501

        :param street_nr_last_suffix: The street_nr_last_suffix of this PlaceRefOrValue.
        :type street_nr_last_suffix: str
        """

        self._street_nr_last_suffix = street_nr_last_suffix

    @property
    def street_nr_suffix(self) -> str:
        """Gets the street_nr_suffix of this PlaceRefOrValue.

        the first street number suffix  # noqa: E501

        :return: The street_nr_suffix of this PlaceRefOrValue.
        :rtype: str
        """
        return self._street_nr_suffix

    @street_nr_suffix.setter
    def street_nr_suffix(self, street_nr_suffix: str):
        """Sets the street_nr_suffix of this PlaceRefOrValue.

        the first street number suffix  # noqa: E501

        :param street_nr_suffix: The street_nr_suffix of this PlaceRefOrValue.
        :type street_nr_suffix: str
        """

        self._street_nr_suffix = street_nr_suffix

    @property
    def street_suffix(self) -> str:
        """Gets the street_suffix of this PlaceRefOrValue.

        A modifier denoting a relative direction  # noqa: E501

        :return: The street_suffix of this PlaceRefOrValue.
        :rtype: str
        """
        return self._street_suffix

    @street_suffix.setter
    def street_suffix(self, street_suffix: str):
        """Sets the street_suffix of this PlaceRefOrValue.

        A modifier denoting a relative direction  # noqa: E501

        :param street_suffix: The street_suffix of this PlaceRefOrValue.
        :type street_suffix: str
        """

        self._street_suffix = street_suffix

    @property
    def street_type(self) -> str:
        """Gets the street_type of this PlaceRefOrValue.

        alley, avenue, boulevard, brae, crescent, drive, highway, lane, terrace, parade, place, tarn, way, wharf   # noqa: E501

        :return: The street_type of this PlaceRefOrValue.
        :rtype: str
        """
        return self._street_type

    @street_type.setter
    def street_type(self, street_type: str):
        """Sets the street_type of this PlaceRefOrValue.

        alley, avenue, boulevard, brae, crescent, drive, highway, lane, terrace, parade, place, tarn, way, wharf   # noqa: E501

        :param street_type: The street_type of this PlaceRefOrValue.
        :type street_type: str
        """

        self._street_type = street_type

    @property
    def country_code(self) -> List[StandardIdentifier]:
        """Gets the country_code of this PlaceRefOrValue.

        Country codes are short alphabetic or numeric geographical codes (geocodes) developed to represent countries and dependent areas, for use in data processing and communications. Several different systems have been developed to do this. The term country code frequently refers to ISO 3166-1 alpha-2 or international dialing codes, the E.164 country calling codes.  # noqa: E501

        :return: The country_code of this PlaceRefOrValue.
        :rtype: List[StandardIdentifier]
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code: List[StandardIdentifier]):
        """Sets the country_code of this PlaceRefOrValue.

        Country codes are short alphabetic or numeric geographical codes (geocodes) developed to represent countries and dependent areas, for use in data processing and communications. Several different systems have been developed to do this. The term country code frequently refers to ISO 3166-1 alpha-2 or international dialing codes, the E.164 country calling codes.  # noqa: E501

        :param country_code: The country_code of this PlaceRefOrValue.
        :type country_code: List[StandardIdentifier]
        """

        self._country_code = country_code

    @property
    def geographic_location(self) -> GeographicLocationRefOrValue:
        """Gets the geographic_location of this PlaceRefOrValue.


        :return: The geographic_location of this PlaceRefOrValue.
        :rtype: GeographicLocationRefOrValue
        """
        return self._geographic_location

    @geographic_location.setter
    def geographic_location(self, geographic_location: GeographicLocationRefOrValue):
        """Sets the geographic_location of this PlaceRefOrValue.


        :param geographic_location: The geographic_location of this PlaceRefOrValue.
        :type geographic_location: GeographicLocationRefOrValue
        """

        self._geographic_location = geographic_location

    @property
    def geographic_sub_address(self) -> List[GeographicSubAddress]:
        """Gets the geographic_sub_address of this PlaceRefOrValue.

        Collection of sub addresses  # noqa: E501

        :return: The geographic_sub_address of this PlaceRefOrValue.
        :rtype: List[GeographicSubAddress]
        """
        return self._geographic_sub_address

    @geographic_sub_address.setter
    def geographic_sub_address(self, geographic_sub_address: List[GeographicSubAddress]):
        """Sets the geographic_sub_address of this PlaceRefOrValue.

        Collection of sub addresses  # noqa: E501

        :param geographic_sub_address: The geographic_sub_address of this PlaceRefOrValue.
        :type geographic_sub_address: List[GeographicSubAddress]
        """

        self._geographic_sub_address = geographic_sub_address

    @property
    def geographic_address_type(self) -> str:
        """Gets the geographic_address_type of this PlaceRefOrValue.

        Classification of the address, e.g., residential, industrial   # noqa: E501

        :return: The geographic_address_type of this PlaceRefOrValue.
        :rtype: str
        """
        return self._geographic_address_type

    @geographic_address_type.setter
    def geographic_address_type(self, geographic_address_type: str):
        """Sets the geographic_address_type of this PlaceRefOrValue.

        Classification of the address, e.g., residential, industrial   # noqa: E501

        :param geographic_address_type: The geographic_address_type of this PlaceRefOrValue.
        :type geographic_address_type: str
        """

        self._geographic_address_type = geographic_address_type

    @property
    def geographic_site(self) -> GeographicSiteRefOrValue:
        """Gets the geographic_site of this PlaceRefOrValue.


        :return: The geographic_site of this PlaceRefOrValue.
        :rtype: GeographicSiteRefOrValue
        """
        return self._geographic_site

    @geographic_site.setter
    def geographic_site(self, geographic_site: GeographicSiteRefOrValue):
        """Sets the geographic_site of this PlaceRefOrValue.


        :param geographic_site: The geographic_site of this PlaceRefOrValue.
        :type geographic_site: GeographicSiteRefOrValue
        """

        self._geographic_site = geographic_site

    @property
    def geographic_address_relationship(self) -> List[GeographicAddressRelationship]:
        """Gets the geographic_address_relationship of this PlaceRefOrValue.

        A list of geographic addresses relationships. Represents a relationship between geographic addresses  # noqa: E501

        :return: The geographic_address_relationship of this PlaceRefOrValue.
        :rtype: List[GeographicAddressRelationship]
        """
        return self._geographic_address_relationship

    @geographic_address_relationship.setter
    def geographic_address_relationship(self, geographic_address_relationship: List[GeographicAddressRelationship]):
        """Sets the geographic_address_relationship of this PlaceRefOrValue.

        A list of geographic addresses relationships. Represents a relationship between geographic addresses  # noqa: E501

        :param geographic_address_relationship: The geographic_address_relationship of this PlaceRefOrValue.
        :type geographic_address_relationship: List[GeographicAddressRelationship]
        """

        self._geographic_address_relationship = geographic_address_relationship

    @property
    def name(self) -> str:
        """Gets the name of this PlaceRefOrValue.

        Name of the referred entity.  # noqa: E501

        :return: The name of this PlaceRefOrValue.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this PlaceRefOrValue.

        Name of the referred entity.  # noqa: E501

        :param name: The name of this PlaceRefOrValue.
        :type name: str
        """

        self._name = name

    @property
    def referred_type(self) -> str:
        """Gets the referred_type of this PlaceRefOrValue.

        The actual type of the target instance when needed for disambiguation.  # noqa: E501

        :return: The referred_type of this PlaceRefOrValue.
        :rtype: str
        """
        return self._referred_type

    @referred_type.setter
    def referred_type(self, referred_type: str):
        """Sets the referred_type of this PlaceRefOrValue.

        The actual type of the target instance when needed for disambiguation.  # noqa: E501

        :param referred_type: The referred_type of this PlaceRefOrValue.
        :type referred_type: str
        """

        self._referred_type = referred_type
