from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.service import Service
from openapi_server import util

from openapi_server.models.service import Service  # noqa: E501

class ServiceOperatingStatusChangeEventPayload(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, service=None):  # noqa: E501
        """ServiceOperatingStatusChangeEventPayload - a model defined in OpenAPI

        :param service: The service of this ServiceOperatingStatusChangeEventPayload.  # noqa: E501
        :type service: Service
        """
        self.openapi_types = {
            'service': Service
        }

        self.attribute_map = {
            'service': 'service'
        }

        self._service = service

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceOperatingStatusChangeEventPayload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceOperatingStatusChangeEventPayload of this ServiceOperatingStatusChangeEventPayload.  # noqa: E501
        :rtype: ServiceOperatingStatusChangeEventPayload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service(self) -> Service:
        """Gets the service of this ServiceOperatingStatusChangeEventPayload.


        :return: The service of this ServiceOperatingStatusChangeEventPayload.
        :rtype: Service
        """
        return self._service

    @service.setter
    def service(self, service: Service):
        """Sets the service of this ServiceOperatingStatusChangeEventPayload.


        :param service: The service of this ServiceOperatingStatusChangeEventPayload.
        :type service: Service
        """

        self._service = service
