/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.19.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Error;
import org.openapitools.model.ResourceAttributeValueChangeEvent;
import org.openapitools.model.ResourceCreateEvent;
import org.openapitools.model.ResourceDeleteEvent;
import org.openapitools.model.ResourceStateChangeEvent;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-07T14:49:43.055954217+01:00[Europe/Paris]", comments = "Generator version: 7.19.0-SNAPSHOT")
@Validated
@Tag(name = "notification listener", description = "Notifications for Resource Lifecycle and event notifications")
public interface ListenerApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_RESOURCE_ATTRIBUTE_VALUE_CHANGE_EVENT = "/listener/resourceAttributeValueChangeEvent";
    /**
     * POST /listener/resourceAttributeValueChangeEvent : Client listener for entity ResourceAttributeValueChangeEvent
     * Example of a client listener for receiving the notification ResourceAttributeValueChangeEvent
     *
     * @param resourceAttributeValueChangeEvent Resource attributeValueChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "resourceAttributeValueChangeEvent",
        summary = "Client listener for entity ResourceAttributeValueChangeEvent",
        description = "Example of a client listener for receiving the notification ResourceAttributeValueChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"@type\":\"Error\",\"code\":\"ERR001\",\"reason\":\"Missing information\",\"message\":\"Please provide the additional example information\",\"referenceError\":\"https://host/errors\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_RESOURCE_ATTRIBUTE_VALUE_CHANGE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> resourceAttributeValueChangeEvent(
        @Parameter(name = "ResourceAttributeValueChangeEvent", description = "Resource attributeValueChange Event payload", required = true) @Valid @RequestBody ResourceAttributeValueChangeEvent resourceAttributeValueChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RESOURCE_CREATE_EVENT = "/listener/resourceCreateEvent";
    /**
     * POST /listener/resourceCreateEvent : Client listener for entity ResourceCreateEvent
     * Example of a client listener for receiving the notification ResourceCreateEvent
     *
     * @param resourceCreateEvent Resource create Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "resourceCreateEvent",
        summary = "Client listener for entity ResourceCreateEvent",
        description = "Example of a client listener for receiving the notification ResourceCreateEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"@type\":\"Error\",\"code\":\"ERR001\",\"reason\":\"Missing information\",\"message\":\"Please provide the additional example information\",\"referenceError\":\"https://host/errors\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_RESOURCE_CREATE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> resourceCreateEvent(
        @Parameter(name = "ResourceCreateEvent", description = "Resource create Event payload", required = true) @Valid @RequestBody ResourceCreateEvent resourceCreateEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RESOURCE_DELETE_EVENT = "/listener/resourceDeleteEvent";
    /**
     * POST /listener/resourceDeleteEvent : Client listener for entity ResourceDeleteEvent
     * Example of a client listener for receiving the notification ResourceDeleteEvent
     *
     * @param resourceDeleteEvent Resource delete Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "resourceDeleteEvent",
        summary = "Client listener for entity ResourceDeleteEvent",
        description = "Example of a client listener for receiving the notification ResourceDeleteEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"@type\":\"Error\",\"code\":\"ERR001\",\"reason\":\"Missing information\",\"message\":\"Please provide the additional example information\",\"referenceError\":\"https://host/errors\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_RESOURCE_DELETE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> resourceDeleteEvent(
        @Parameter(name = "ResourceDeleteEvent", description = "Resource delete Event payload", required = true) @Valid @RequestBody ResourceDeleteEvent resourceDeleteEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RESOURCE_STATE_CHANGE_EVENT = "/listener/resourceStateChangeEvent";
    /**
     * POST /listener/resourceStateChangeEvent : Client listener for entity ResourceStateChangeEvent
     * Example of a client listener for receiving the notification ResourceStateChangeEvent
     *
     * @param resourceStateChangeEvent Resource stateChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "resourceStateChangeEvent",
        summary = "Client listener for entity ResourceStateChangeEvent",
        description = "Example of a client listener for receiving the notification ResourceStateChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"@type\":\"Error\",\"code\":\"ERR001\",\"reason\":\"Missing information\",\"message\":\"Please provide the additional example information\",\"referenceError\":\"https://host/errors\"}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ListenerApi.PATH_RESOURCE_STATE_CHANGE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> resourceStateChangeEvent(
        @Parameter(name = "ResourceStateChangeEvent", description = "Resource stateChange Event payload", required = true) @Valid @RequestBody ResourceStateChangeEvent resourceStateChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
