package org.openapitools.model;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import org.openapitools.model.IndividualRef;
import org.openapitools.model.OrganizationRef;
import org.openapitools.model.PartyRef;
import org.openapitools.model.PartyRoleRef;
import org.openapitools.model.ResourceRef;
import org.openapitools.model.ResourceRoleRef;
import org.springframework.lang.Nullable;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import javax.annotation.Generated;


@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = IndividualRef.class, name = "IndividualRef"),
  @JsonSubTypes.Type(value = OrganizationRef.class, name = "OrganizationRef"),
  @JsonSubTypes.Type(value = PartyRef.class, name = "PartyRef"),
  @JsonSubTypes.Type(value = PartyRoleRef.class, name = "PartyRoleRef"),
  @JsonSubTypes.Type(value = ResourceRef.class, name = "ResourceRef"),
  @JsonSubTypes.Type(value = ResourceRoleRef.class, name = "ResourceRoleRef")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-07T14:50:13.349318156+01:00[Europe/Paris]", comments = "Generator version: 7.19.0-SNAPSHOT")
public interface SecurityPrincipalRef {
    public String getAtType();
}
