from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.characteristic_mvo import CharacteristicMVO
from openapi_server.models.characteristic_relationship_mvo import CharacteristicRelationshipMVO
from openapi_server import util

from openapi_server.models.characteristic_mvo import CharacteristicMVO  # noqa: E501
from openapi_server.models.characteristic_relationship_mvo import CharacteristicRelationshipMVO  # noqa: E501

class BooleanArrayCharacteristicMVO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, base_type=None, schema_location=None, id=None, name=None, value_type=None, characteristic_relationship=None, value=None):  # noqa: E501
        """BooleanArrayCharacteristicMVO - a model defined in OpenAPI

        :param type: The type of this BooleanArrayCharacteristicMVO.  # noqa: E501
        :type type: str
        :param base_type: The base_type of this BooleanArrayCharacteristicMVO.  # noqa: E501
        :type base_type: str
        :param schema_location: The schema_location of this BooleanArrayCharacteristicMVO.  # noqa: E501
        :type schema_location: str
        :param id: The id of this BooleanArrayCharacteristicMVO.  # noqa: E501
        :type id: str
        :param name: The name of this BooleanArrayCharacteristicMVO.  # noqa: E501
        :type name: str
        :param value_type: The value_type of this BooleanArrayCharacteristicMVO.  # noqa: E501
        :type value_type: str
        :param characteristic_relationship: The characteristic_relationship of this BooleanArrayCharacteristicMVO.  # noqa: E501
        :type characteristic_relationship: List[CharacteristicRelationshipMVO]
        :param value: The value of this BooleanArrayCharacteristicMVO.  # noqa: E501
        :type value: List[bool]
        """
        self.openapi_types = {
            'type': str,
            'base_type': str,
            'schema_location': str,
            'id': str,
            'name': str,
            'value_type': str,
            'characteristic_relationship': List[CharacteristicRelationshipMVO],
            'value': List[bool]
        }

        self.attribute_map = {
            'type': '@type',
            'base_type': '@baseType',
            'schema_location': '@schemaLocation',
            'id': 'id',
            'name': 'name',
            'value_type': 'valueType',
            'characteristic_relationship': 'characteristicRelationship',
            'value': 'value'
        }

        self._type = type
        self._base_type = base_type
        self._schema_location = schema_location
        self._id = id
        self._name = name
        self._value_type = value_type
        self._characteristic_relationship = characteristic_relationship
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'BooleanArrayCharacteristicMVO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BooleanArrayCharacteristic_MVO of this BooleanArrayCharacteristicMVO.  # noqa: E501
        :rtype: BooleanArrayCharacteristicMVO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this BooleanArrayCharacteristicMVO.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :return: The type of this BooleanArrayCharacteristicMVO.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this BooleanArrayCharacteristicMVO.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :param type: The type of this BooleanArrayCharacteristicMVO.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def base_type(self) -> str:
        """Gets the base_type of this BooleanArrayCharacteristicMVO.

        When sub-classing, this defines the super-class  # noqa: E501

        :return: The base_type of this BooleanArrayCharacteristicMVO.
        :rtype: str
        """
        return self._base_type

    @base_type.setter
    def base_type(self, base_type: str):
        """Sets the base_type of this BooleanArrayCharacteristicMVO.

        When sub-classing, this defines the super-class  # noqa: E501

        :param base_type: The base_type of this BooleanArrayCharacteristicMVO.
        :type base_type: str
        """

        self._base_type = base_type

    @property
    def schema_location(self) -> str:
        """Gets the schema_location of this BooleanArrayCharacteristicMVO.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :return: The schema_location of this BooleanArrayCharacteristicMVO.
        :rtype: str
        """
        return self._schema_location

    @schema_location.setter
    def schema_location(self, schema_location: str):
        """Sets the schema_location of this BooleanArrayCharacteristicMVO.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :param schema_location: The schema_location of this BooleanArrayCharacteristicMVO.
        :type schema_location: str
        """

        self._schema_location = schema_location

    @property
    def id(self) -> str:
        """Gets the id of this BooleanArrayCharacteristicMVO.

        Unique identifier of the characteristic  # noqa: E501

        :return: The id of this BooleanArrayCharacteristicMVO.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this BooleanArrayCharacteristicMVO.

        Unique identifier of the characteristic  # noqa: E501

        :param id: The id of this BooleanArrayCharacteristicMVO.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this BooleanArrayCharacteristicMVO.

        Name of the characteristic  # noqa: E501

        :return: The name of this BooleanArrayCharacteristicMVO.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this BooleanArrayCharacteristicMVO.

        Name of the characteristic  # noqa: E501

        :param name: The name of this BooleanArrayCharacteristicMVO.
        :type name: str
        """

        self._name = name

    @property
    def value_type(self) -> str:
        """Gets the value_type of this BooleanArrayCharacteristicMVO.

        Data type of the value of the characteristic  # noqa: E501

        :return: The value_type of this BooleanArrayCharacteristicMVO.
        :rtype: str
        """
        return self._value_type

    @value_type.setter
    def value_type(self, value_type: str):
        """Sets the value_type of this BooleanArrayCharacteristicMVO.

        Data type of the value of the characteristic  # noqa: E501

        :param value_type: The value_type of this BooleanArrayCharacteristicMVO.
        :type value_type: str
        """

        self._value_type = value_type

    @property
    def characteristic_relationship(self) -> List[CharacteristicRelationshipMVO]:
        """Gets the characteristic_relationship of this BooleanArrayCharacteristicMVO.


        :return: The characteristic_relationship of this BooleanArrayCharacteristicMVO.
        :rtype: List[CharacteristicRelationshipMVO]
        """
        return self._characteristic_relationship

    @characteristic_relationship.setter
    def characteristic_relationship(self, characteristic_relationship: List[CharacteristicRelationshipMVO]):
        """Sets the characteristic_relationship of this BooleanArrayCharacteristicMVO.


        :param characteristic_relationship: The characteristic_relationship of this BooleanArrayCharacteristicMVO.
        :type characteristic_relationship: List[CharacteristicRelationshipMVO]
        """

        self._characteristic_relationship = characteristic_relationship

    @property
    def value(self) -> List[bool]:
        """Gets the value of this BooleanArrayCharacteristicMVO.


        :return: The value of this BooleanArrayCharacteristicMVO.
        :rtype: List[bool]
        """
        return self._value

    @value.setter
    def value(self, value: List[bool]):
        """Sets the value of this BooleanArrayCharacteristicMVO.


        :param value: The value of this BooleanArrayCharacteristicMVO.
        :type value: List[bool]
        """

        self._value = value
