from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CancelOrderFVO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, base_type=None, schema_location=None, requested_cancellation_date=None, cancellation_reason=None):  # noqa: E501
        """CancelOrderFVO - a model defined in OpenAPI

        :param type: The type of this CancelOrderFVO.  # noqa: E501
        :type type: str
        :param base_type: The base_type of this CancelOrderFVO.  # noqa: E501
        :type base_type: str
        :param schema_location: The schema_location of this CancelOrderFVO.  # noqa: E501
        :type schema_location: str
        :param requested_cancellation_date: The requested_cancellation_date of this CancelOrderFVO.  # noqa: E501
        :type requested_cancellation_date: datetime
        :param cancellation_reason: The cancellation_reason of this CancelOrderFVO.  # noqa: E501
        :type cancellation_reason: str
        """
        self.openapi_types = {
            'type': str,
            'base_type': str,
            'schema_location': str,
            'requested_cancellation_date': datetime,
            'cancellation_reason': str
        }

        self.attribute_map = {
            'type': '@type',
            'base_type': '@baseType',
            'schema_location': '@schemaLocation',
            'requested_cancellation_date': 'requestedCancellationDate',
            'cancellation_reason': 'cancellationReason'
        }

        self._type = type
        self._base_type = base_type
        self._schema_location = schema_location
        self._requested_cancellation_date = requested_cancellation_date
        self._cancellation_reason = cancellation_reason

    @classmethod
    def from_dict(cls, dikt) -> 'CancelOrderFVO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CancelOrder_FVO of this CancelOrderFVO.  # noqa: E501
        :rtype: CancelOrderFVO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this CancelOrderFVO.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :return: The type of this CancelOrderFVO.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this CancelOrderFVO.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :param type: The type of this CancelOrderFVO.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def base_type(self) -> str:
        """Gets the base_type of this CancelOrderFVO.

        When sub-classing, this defines the super-class  # noqa: E501

        :return: The base_type of this CancelOrderFVO.
        :rtype: str
        """
        return self._base_type

    @base_type.setter
    def base_type(self, base_type: str):
        """Sets the base_type of this CancelOrderFVO.

        When sub-classing, this defines the super-class  # noqa: E501

        :param base_type: The base_type of this CancelOrderFVO.
        :type base_type: str
        """

        self._base_type = base_type

    @property
    def schema_location(self) -> str:
        """Gets the schema_location of this CancelOrderFVO.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :return: The schema_location of this CancelOrderFVO.
        :rtype: str
        """
        return self._schema_location

    @schema_location.setter
    def schema_location(self, schema_location: str):
        """Sets the schema_location of this CancelOrderFVO.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :param schema_location: The schema_location of this CancelOrderFVO.
        :type schema_location: str
        """

        self._schema_location = schema_location

    @property
    def requested_cancellation_date(self) -> datetime:
        """Gets the requested_cancellation_date of this CancelOrderFVO.

        Date when the submitter wants the order to be cancelled  # noqa: E501

        :return: The requested_cancellation_date of this CancelOrderFVO.
        :rtype: datetime
        """
        return self._requested_cancellation_date

    @requested_cancellation_date.setter
    def requested_cancellation_date(self, requested_cancellation_date: datetime):
        """Sets the requested_cancellation_date of this CancelOrderFVO.

        Date when the submitter wants the order to be cancelled  # noqa: E501

        :param requested_cancellation_date: The requested_cancellation_date of this CancelOrderFVO.
        :type requested_cancellation_date: datetime
        """

        self._requested_cancellation_date = requested_cancellation_date

    @property
    def cancellation_reason(self) -> str:
        """Gets the cancellation_reason of this CancelOrderFVO.

        Reason why the order is cancelled.  # noqa: E501

        :return: The cancellation_reason of this CancelOrderFVO.
        :rtype: str
        """
        return self._cancellation_reason

    @cancellation_reason.setter
    def cancellation_reason(self, cancellation_reason: str):
        """Sets the cancellation_reason of this CancelOrderFVO.

        Reason why the order is cancelled.  # noqa: E501

        :param cancellation_reason: The cancellation_reason of this CancelOrderFVO.
        :type cancellation_reason: str
        """

        self._cancellation_reason = cancellation_reason
