from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ExternalReferenceMVO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, base_type=None, schema_location=None, external_reference_type=None, href=None, name=None, id=None):  # noqa: E501
        """ExternalReferenceMVO - a model defined in OpenAPI

        :param type: The type of this ExternalReferenceMVO.  # noqa: E501
        :type type: str
        :param base_type: The base_type of this ExternalReferenceMVO.  # noqa: E501
        :type base_type: str
        :param schema_location: The schema_location of this ExternalReferenceMVO.  # noqa: E501
        :type schema_location: str
        :param external_reference_type: The external_reference_type of this ExternalReferenceMVO.  # noqa: E501
        :type external_reference_type: str
        :param href: The href of this ExternalReferenceMVO.  # noqa: E501
        :type href: str
        :param name: The name of this ExternalReferenceMVO.  # noqa: E501
        :type name: str
        :param id: The id of this ExternalReferenceMVO.  # noqa: E501
        :type id: str
        """
        self.openapi_types = {
            'type': str,
            'base_type': str,
            'schema_location': str,
            'external_reference_type': str,
            'href': str,
            'name': str,
            'id': str
        }

        self.attribute_map = {
            'type': '@type',
            'base_type': '@baseType',
            'schema_location': '@schemaLocation',
            'external_reference_type': 'externalReferenceType',
            'href': 'href',
            'name': 'name',
            'id': 'id'
        }

        self._type = type
        self._base_type = base_type
        self._schema_location = schema_location
        self._external_reference_type = external_reference_type
        self._href = href
        self._name = name
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'ExternalReferenceMVO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExternalReference_MVO of this ExternalReferenceMVO.  # noqa: E501
        :rtype: ExternalReferenceMVO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ExternalReferenceMVO.


        :return: The type of this ExternalReferenceMVO.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ExternalReferenceMVO.


        :param type: The type of this ExternalReferenceMVO.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def base_type(self) -> str:
        """Gets the base_type of this ExternalReferenceMVO.

        When sub-classing, this defines the super-class  # noqa: E501

        :return: The base_type of this ExternalReferenceMVO.
        :rtype: str
        """
        return self._base_type

    @base_type.setter
    def base_type(self, base_type: str):
        """Sets the base_type of this ExternalReferenceMVO.

        When sub-classing, this defines the super-class  # noqa: E501

        :param base_type: The base_type of this ExternalReferenceMVO.
        :type base_type: str
        """

        self._base_type = base_type

    @property
    def schema_location(self) -> str:
        """Gets the schema_location of this ExternalReferenceMVO.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :return: The schema_location of this ExternalReferenceMVO.
        :rtype: str
        """
        return self._schema_location

    @schema_location.setter
    def schema_location(self, schema_location: str):
        """Sets the schema_location of this ExternalReferenceMVO.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :param schema_location: The schema_location of this ExternalReferenceMVO.
        :type schema_location: str
        """

        self._schema_location = schema_location

    @property
    def external_reference_type(self) -> str:
        """Gets the external_reference_type of this ExternalReferenceMVO.

        Type of the external reference  # noqa: E501

        :return: The external_reference_type of this ExternalReferenceMVO.
        :rtype: str
        """
        return self._external_reference_type

    @external_reference_type.setter
    def external_reference_type(self, external_reference_type: str):
        """Sets the external_reference_type of this ExternalReferenceMVO.

        Type of the external reference  # noqa: E501

        :param external_reference_type: The external_reference_type of this ExternalReferenceMVO.
        :type external_reference_type: str
        """

        self._external_reference_type = external_reference_type

    @property
    def href(self) -> str:
        """Gets the href of this ExternalReferenceMVO.

        Hyperlink reference  # noqa: E501

        :return: The href of this ExternalReferenceMVO.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this ExternalReferenceMVO.

        Hyperlink reference  # noqa: E501

        :param href: The href of this ExternalReferenceMVO.
        :type href: str
        """

        self._href = href

    @property
    def name(self) -> str:
        """Gets the name of this ExternalReferenceMVO.

        name given to the external reference  # noqa: E501

        :return: The name of this ExternalReferenceMVO.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ExternalReferenceMVO.

        name given to the external reference  # noqa: E501

        :param name: The name of this ExternalReferenceMVO.
        :type name: str
        """

        self._name = name

    @property
    def id(self) -> str:
        """Gets the id of this ExternalReferenceMVO.

        unique identifier  # noqa: E501

        :return: The id of this ExternalReferenceMVO.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ExternalReferenceMVO.

        unique identifier  # noqa: E501

        :param id: The id of this ExternalReferenceMVO.
        :type id: str
        """

        self._id = id
