from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.characteristic_fvo import CharacteristicFVO
from openapi_server.models.feature_relationship_fvo import FeatureRelationshipFVO
from openapi_server.models.policy_ref_fvo import PolicyRefFVO
from openapi_server import util

from openapi_server.models.characteristic_fvo import CharacteristicFVO  # noqa: E501
from openapi_server.models.feature_relationship_fvo import FeatureRelationshipFVO  # noqa: E501
from openapi_server.models.policy_ref_fvo import PolicyRefFVO  # noqa: E501

class FeatureFVO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, base_type=None, schema_location=None, is_bundle=None, feature_relationship=None, feature_characteristic=None, policy_constraint=None, is_enabled=None, id=None, name=None):  # noqa: E501
        """FeatureFVO - a model defined in OpenAPI

        :param type: The type of this FeatureFVO.  # noqa: E501
        :type type: str
        :param base_type: The base_type of this FeatureFVO.  # noqa: E501
        :type base_type: str
        :param schema_location: The schema_location of this FeatureFVO.  # noqa: E501
        :type schema_location: str
        :param is_bundle: The is_bundle of this FeatureFVO.  # noqa: E501
        :type is_bundle: bool
        :param feature_relationship: The feature_relationship of this FeatureFVO.  # noqa: E501
        :type feature_relationship: List[FeatureRelationshipFVO]
        :param feature_characteristic: The feature_characteristic of this FeatureFVO.  # noqa: E501
        :type feature_characteristic: List[CharacteristicFVO]
        :param policy_constraint: The policy_constraint of this FeatureFVO.  # noqa: E501
        :type policy_constraint: List[PolicyRefFVO]
        :param is_enabled: The is_enabled of this FeatureFVO.  # noqa: E501
        :type is_enabled: bool
        :param id: The id of this FeatureFVO.  # noqa: E501
        :type id: str
        :param name: The name of this FeatureFVO.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'type': str,
            'base_type': str,
            'schema_location': str,
            'is_bundle': bool,
            'feature_relationship': List[FeatureRelationshipFVO],
            'feature_characteristic': List[CharacteristicFVO],
            'policy_constraint': List[PolicyRefFVO],
            'is_enabled': bool,
            'id': str,
            'name': str
        }

        self.attribute_map = {
            'type': '@type',
            'base_type': '@baseType',
            'schema_location': '@schemaLocation',
            'is_bundle': 'isBundle',
            'feature_relationship': 'featureRelationship',
            'feature_characteristic': 'featureCharacteristic',
            'policy_constraint': 'policyConstraint',
            'is_enabled': 'isEnabled',
            'id': 'id',
            'name': 'name'
        }

        self._type = type
        self._base_type = base_type
        self._schema_location = schema_location
        self._is_bundle = is_bundle
        self._feature_relationship = feature_relationship
        self._feature_characteristic = feature_characteristic
        self._policy_constraint = policy_constraint
        self._is_enabled = is_enabled
        self._id = id
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'FeatureFVO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Feature_FVO of this FeatureFVO.  # noqa: E501
        :rtype: FeatureFVO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this FeatureFVO.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :return: The type of this FeatureFVO.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this FeatureFVO.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :param type: The type of this FeatureFVO.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def base_type(self) -> str:
        """Gets the base_type of this FeatureFVO.

        When sub-classing, this defines the super-class  # noqa: E501

        :return: The base_type of this FeatureFVO.
        :rtype: str
        """
        return self._base_type

    @base_type.setter
    def base_type(self, base_type: str):
        """Sets the base_type of this FeatureFVO.

        When sub-classing, this defines the super-class  # noqa: E501

        :param base_type: The base_type of this FeatureFVO.
        :type base_type: str
        """

        self._base_type = base_type

    @property
    def schema_location(self) -> str:
        """Gets the schema_location of this FeatureFVO.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :return: The schema_location of this FeatureFVO.
        :rtype: str
        """
        return self._schema_location

    @schema_location.setter
    def schema_location(self, schema_location: str):
        """Sets the schema_location of this FeatureFVO.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :param schema_location: The schema_location of this FeatureFVO.
        :type schema_location: str
        """

        self._schema_location = schema_location

    @property
    def is_bundle(self) -> bool:
        """Gets the is_bundle of this FeatureFVO.

        True if this is a feature group. Default is false.  # noqa: E501

        :return: The is_bundle of this FeatureFVO.
        :rtype: bool
        """
        return self._is_bundle

    @is_bundle.setter
    def is_bundle(self, is_bundle: bool):
        """Sets the is_bundle of this FeatureFVO.

        True if this is a feature group. Default is false.  # noqa: E501

        :param is_bundle: The is_bundle of this FeatureFVO.
        :type is_bundle: bool
        """

        self._is_bundle = is_bundle

    @property
    def feature_relationship(self) -> List[FeatureRelationshipFVO]:
        """Gets the feature_relationship of this FeatureFVO.


        :return: The feature_relationship of this FeatureFVO.
        :rtype: List[FeatureRelationshipFVO]
        """
        return self._feature_relationship

    @feature_relationship.setter
    def feature_relationship(self, feature_relationship: List[FeatureRelationshipFVO]):
        """Sets the feature_relationship of this FeatureFVO.


        :param feature_relationship: The feature_relationship of this FeatureFVO.
        :type feature_relationship: List[FeatureRelationshipFVO]
        """

        self._feature_relationship = feature_relationship

    @property
    def feature_characteristic(self) -> List[CharacteristicFVO]:
        """Gets the feature_characteristic of this FeatureFVO.

        This is a list of Characteristics for a particular feature.  # noqa: E501

        :return: The feature_characteristic of this FeatureFVO.
        :rtype: List[CharacteristicFVO]
        """
        return self._feature_characteristic

    @feature_characteristic.setter
    def feature_characteristic(self, feature_characteristic: List[CharacteristicFVO]):
        """Sets the feature_characteristic of this FeatureFVO.

        This is a list of Characteristics for a particular feature.  # noqa: E501

        :param feature_characteristic: The feature_characteristic of this FeatureFVO.
        :type feature_characteristic: List[CharacteristicFVO]
        """

        self._feature_characteristic = feature_characteristic

    @property
    def policy_constraint(self) -> List[PolicyRefFVO]:
        """Gets the policy_constraint of this FeatureFVO.

        Reference to mangage a list of feature specification policy constraints  # noqa: E501

        :return: The policy_constraint of this FeatureFVO.
        :rtype: List[PolicyRefFVO]
        """
        return self._policy_constraint

    @policy_constraint.setter
    def policy_constraint(self, policy_constraint: List[PolicyRefFVO]):
        """Sets the policy_constraint of this FeatureFVO.

        Reference to mangage a list of feature specification policy constraints  # noqa: E501

        :param policy_constraint: The policy_constraint of this FeatureFVO.
        :type policy_constraint: List[PolicyRefFVO]
        """

        self._policy_constraint = policy_constraint

    @property
    def is_enabled(self) -> bool:
        """Gets the is_enabled of this FeatureFVO.

        True if this feature is enabled. Default is true.  # noqa: E501

        :return: The is_enabled of this FeatureFVO.
        :rtype: bool
        """
        return self._is_enabled

    @is_enabled.setter
    def is_enabled(self, is_enabled: bool):
        """Sets the is_enabled of this FeatureFVO.

        True if this feature is enabled. Default is true.  # noqa: E501

        :param is_enabled: The is_enabled of this FeatureFVO.
        :type is_enabled: bool
        """

        self._is_enabled = is_enabled

    @property
    def id(self) -> str:
        """Gets the id of this FeatureFVO.

        unique identifier  # noqa: E501

        :return: The id of this FeatureFVO.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this FeatureFVO.

        unique identifier  # noqa: E501

        :param id: The id of this FeatureFVO.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this FeatureFVO.

        This is the name for the feature.  # noqa: E501

        :return: The name of this FeatureFVO.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this FeatureFVO.

        This is the name for the feature.  # noqa: E501

        :param name: The name of this FeatureFVO.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
