from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.attachment_ref_or_value_fvo import AttachmentRefOrValueFVO
from openapi_server.models.characteristic_fvo import CharacteristicFVO
from openapi_server.models.entity_ref import EntityRef
from openapi_server.models.entity_relationship_fvo import EntityRelationshipFVO
from openapi_server.models.intent_expression import IntentExpression
from openapi_server.models.related_party_ref_or_party_role_ref_fvo import RelatedPartyRefOrPartyRoleRefFVO
from openapi_server.models.time_period import TimePeriod
from openapi_server import util

from openapi_server.models.attachment_ref_or_value_fvo import AttachmentRefOrValueFVO  # noqa: E501
from openapi_server.models.characteristic_fvo import CharacteristicFVO  # noqa: E501
from openapi_server.models.entity_ref import EntityRef  # noqa: E501
from openapi_server.models.entity_relationship_fvo import EntityRelationshipFVO  # noqa: E501
from openapi_server.models.intent_expression import IntentExpression  # noqa: E501
from openapi_server.models.related_party_ref_or_party_role_ref_fvo import RelatedPartyRefOrPartyRoleRefFVO  # noqa: E501
from openapi_server.models.time_period import TimePeriod  # noqa: E501

class IntentFVO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, base_type=None, schema_location=None, href=None, id=None, description=None, valid_for=None, is_bundle=None, priority=None, status_change_date=None, context=None, version=None, intent_specification=None, intent_relationship=None, characteristic=None, related_party=None, attachment=None, name=None, expression=None, creation_date=None, last_update=None, lifecycle_status=None):  # noqa: E501
        """IntentFVO - a model defined in OpenAPI

        :param type: The type of this IntentFVO.  # noqa: E501
        :type type: str
        :param base_type: The base_type of this IntentFVO.  # noqa: E501
        :type base_type: str
        :param schema_location: The schema_location of this IntentFVO.  # noqa: E501
        :type schema_location: str
        :param href: The href of this IntentFVO.  # noqa: E501
        :type href: str
        :param id: The id of this IntentFVO.  # noqa: E501
        :type id: str
        :param description: The description of this IntentFVO.  # noqa: E501
        :type description: str
        :param valid_for: The valid_for of this IntentFVO.  # noqa: E501
        :type valid_for: TimePeriod
        :param is_bundle: The is_bundle of this IntentFVO.  # noqa: E501
        :type is_bundle: bool
        :param priority: The priority of this IntentFVO.  # noqa: E501
        :type priority: str
        :param status_change_date: The status_change_date of this IntentFVO.  # noqa: E501
        :type status_change_date: datetime
        :param context: The context of this IntentFVO.  # noqa: E501
        :type context: str
        :param version: The version of this IntentFVO.  # noqa: E501
        :type version: str
        :param intent_specification: The intent_specification of this IntentFVO.  # noqa: E501
        :type intent_specification: EntityRef
        :param intent_relationship: The intent_relationship of this IntentFVO.  # noqa: E501
        :type intent_relationship: List[EntityRelationshipFVO]
        :param characteristic: The characteristic of this IntentFVO.  # noqa: E501
        :type characteristic: List[CharacteristicFVO]
        :param related_party: The related_party of this IntentFVO.  # noqa: E501
        :type related_party: List[RelatedPartyRefOrPartyRoleRefFVO]
        :param attachment: The attachment of this IntentFVO.  # noqa: E501
        :type attachment: List[AttachmentRefOrValueFVO]
        :param name: The name of this IntentFVO.  # noqa: E501
        :type name: str
        :param expression: The expression of this IntentFVO.  # noqa: E501
        :type expression: IntentExpression
        :param creation_date: The creation_date of this IntentFVO.  # noqa: E501
        :type creation_date: datetime
        :param last_update: The last_update of this IntentFVO.  # noqa: E501
        :type last_update: datetime
        :param lifecycle_status: The lifecycle_status of this IntentFVO.  # noqa: E501
        :type lifecycle_status: str
        """
        self.openapi_types = {
            'type': str,
            'base_type': str,
            'schema_location': str,
            'href': str,
            'id': str,
            'description': str,
            'valid_for': TimePeriod,
            'is_bundle': bool,
            'priority': str,
            'status_change_date': datetime,
            'context': str,
            'version': str,
            'intent_specification': EntityRef,
            'intent_relationship': List[EntityRelationshipFVO],
            'characteristic': List[CharacteristicFVO],
            'related_party': List[RelatedPartyRefOrPartyRoleRefFVO],
            'attachment': List[AttachmentRefOrValueFVO],
            'name': str,
            'expression': IntentExpression,
            'creation_date': datetime,
            'last_update': datetime,
            'lifecycle_status': str
        }

        self.attribute_map = {
            'type': '@type',
            'base_type': '@baseType',
            'schema_location': '@schemaLocation',
            'href': 'href',
            'id': 'id',
            'description': 'description',
            'valid_for': 'validFor',
            'is_bundle': 'isBundle',
            'priority': 'priority',
            'status_change_date': 'statusChangeDate',
            'context': 'context',
            'version': 'version',
            'intent_specification': 'intentSpecification',
            'intent_relationship': 'intentRelationship',
            'characteristic': 'characteristic',
            'related_party': 'relatedParty',
            'attachment': 'attachment',
            'name': 'name',
            'expression': 'expression',
            'creation_date': 'creationDate',
            'last_update': 'lastUpdate',
            'lifecycle_status': 'lifecycleStatus'
        }

        self._type = type
        self._base_type = base_type
        self._schema_location = schema_location
        self._href = href
        self._id = id
        self._description = description
        self._valid_for = valid_for
        self._is_bundle = is_bundle
        self._priority = priority
        self._status_change_date = status_change_date
        self._context = context
        self._version = version
        self._intent_specification = intent_specification
        self._intent_relationship = intent_relationship
        self._characteristic = characteristic
        self._related_party = related_party
        self._attachment = attachment
        self._name = name
        self._expression = expression
        self._creation_date = creation_date
        self._last_update = last_update
        self._lifecycle_status = lifecycle_status

    @classmethod
    def from_dict(cls, dikt) -> 'IntentFVO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Intent_FVO of this IntentFVO.  # noqa: E501
        :rtype: IntentFVO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this IntentFVO.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :return: The type of this IntentFVO.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this IntentFVO.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :param type: The type of this IntentFVO.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def base_type(self) -> str:
        """Gets the base_type of this IntentFVO.

        When sub-classing, this defines the super-class  # noqa: E501

        :return: The base_type of this IntentFVO.
        :rtype: str
        """
        return self._base_type

    @base_type.setter
    def base_type(self, base_type: str):
        """Sets the base_type of this IntentFVO.

        When sub-classing, this defines the super-class  # noqa: E501

        :param base_type: The base_type of this IntentFVO.
        :type base_type: str
        """

        self._base_type = base_type

    @property
    def schema_location(self) -> str:
        """Gets the schema_location of this IntentFVO.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :return: The schema_location of this IntentFVO.
        :rtype: str
        """
        return self._schema_location

    @schema_location.setter
    def schema_location(self, schema_location: str):
        """Sets the schema_location of this IntentFVO.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :param schema_location: The schema_location of this IntentFVO.
        :type schema_location: str
        """

        self._schema_location = schema_location

    @property
    def href(self) -> str:
        """Gets the href of this IntentFVO.

        Hyperlink reference  # noqa: E501

        :return: The href of this IntentFVO.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this IntentFVO.

        Hyperlink reference  # noqa: E501

        :param href: The href of this IntentFVO.
        :type href: str
        """

        self._href = href

    @property
    def id(self) -> str:
        """Gets the id of this IntentFVO.

        unique identifier  # noqa: E501

        :return: The id of this IntentFVO.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this IntentFVO.

        unique identifier  # noqa: E501

        :param id: The id of this IntentFVO.
        :type id: str
        """

        self._id = id

    @property
    def description(self) -> str:
        """Gets the description of this IntentFVO.

        The description of the intent.  # noqa: E501

        :return: The description of this IntentFVO.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this IntentFVO.

        The description of the intent.  # noqa: E501

        :param description: The description of this IntentFVO.
        :type description: str
        """

        self._description = description

    @property
    def valid_for(self) -> TimePeriod:
        """Gets the valid_for of this IntentFVO.


        :return: The valid_for of this IntentFVO.
        :rtype: TimePeriod
        """
        return self._valid_for

    @valid_for.setter
    def valid_for(self, valid_for: TimePeriod):
        """Sets the valid_for of this IntentFVO.


        :param valid_for: The valid_for of this IntentFVO.
        :type valid_for: TimePeriod
        """

        self._valid_for = valid_for

    @property
    def is_bundle(self) -> bool:
        """Gets the is_bundle of this IntentFVO.

        isBundle determines whether an intent represents a single intent (false), or a bundle of intents(true).  # noqa: E501

        :return: The is_bundle of this IntentFVO.
        :rtype: bool
        """
        return self._is_bundle

    @is_bundle.setter
    def is_bundle(self, is_bundle: bool):
        """Sets the is_bundle of this IntentFVO.

        isBundle determines whether an intent represents a single intent (false), or a bundle of intents(true).  # noqa: E501

        :param is_bundle: The is_bundle of this IntentFVO.
        :type is_bundle: bool
        """

        self._is_bundle = is_bundle

    @property
    def priority(self) -> str:
        """Gets the priority of this IntentFVO.

        Can be used by intent owner to prioritize intents in an intent management system  # noqa: E501

        :return: The priority of this IntentFVO.
        :rtype: str
        """
        return self._priority

    @priority.setter
    def priority(self, priority: str):
        """Sets the priority of this IntentFVO.

        Can be used by intent owner to prioritize intents in an intent management system  # noqa: E501

        :param priority: The priority of this IntentFVO.
        :type priority: str
        """

        self._priority = priority

    @property
    def status_change_date(self) -> datetime:
        """Gets the status_change_date of this IntentFVO.

        A date time( DateTime). The date that the entity status changed to the current one  # noqa: E501

        :return: The status_change_date of this IntentFVO.
        :rtype: datetime
        """
        return self._status_change_date

    @status_change_date.setter
    def status_change_date(self, status_change_date: datetime):
        """Sets the status_change_date of this IntentFVO.

        A date time( DateTime). The date that the entity status changed to the current one  # noqa: E501

        :param status_change_date: The status_change_date of this IntentFVO.
        :type status_change_date: datetime
        """

        self._status_change_date = status_change_date

    @property
    def context(self) -> str:
        """Gets the context of this IntentFVO.

        A string used to give a context to the intent  # noqa: E501

        :return: The context of this IntentFVO.
        :rtype: str
        """
        return self._context

    @context.setter
    def context(self, context: str):
        """Sets the context of this IntentFVO.

        A string used to give a context to the intent  # noqa: E501

        :param context: The context of this IntentFVO.
        :type context: str
        """

        self._context = context

    @property
    def version(self) -> str:
        """Gets the version of this IntentFVO.

        A field that identifies the specific version of an instance of an intent.  # noqa: E501

        :return: The version of this IntentFVO.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this IntentFVO.

        A field that identifies the specific version of an instance of an intent.  # noqa: E501

        :param version: The version of this IntentFVO.
        :type version: str
        """

        self._version = version

    @property
    def intent_specification(self) -> EntityRef:
        """Gets the intent_specification of this IntentFVO.


        :return: The intent_specification of this IntentFVO.
        :rtype: EntityRef
        """
        return self._intent_specification

    @intent_specification.setter
    def intent_specification(self, intent_specification: EntityRef):
        """Sets the intent_specification of this IntentFVO.


        :param intent_specification: The intent_specification of this IntentFVO.
        :type intent_specification: EntityRef
        """

        self._intent_specification = intent_specification

    @property
    def intent_relationship(self) -> List[EntityRelationshipFVO]:
        """Gets the intent_relationship of this IntentFVO.

        A list of intents related to this intent  # noqa: E501

        :return: The intent_relationship of this IntentFVO.
        :rtype: List[EntityRelationshipFVO]
        """
        return self._intent_relationship

    @intent_relationship.setter
    def intent_relationship(self, intent_relationship: List[EntityRelationshipFVO]):
        """Sets the intent_relationship of this IntentFVO.

        A list of intents related to this intent  # noqa: E501

        :param intent_relationship: The intent_relationship of this IntentFVO.
        :type intent_relationship: List[EntityRelationshipFVO]
        """

        self._intent_relationship = intent_relationship

    @property
    def characteristic(self) -> List[CharacteristicFVO]:
        """Gets the characteristic of this IntentFVO.


        :return: The characteristic of this IntentFVO.
        :rtype: List[CharacteristicFVO]
        """
        return self._characteristic

    @characteristic.setter
    def characteristic(self, characteristic: List[CharacteristicFVO]):
        """Sets the characteristic of this IntentFVO.


        :param characteristic: The characteristic of this IntentFVO.
        :type characteristic: List[CharacteristicFVO]
        """

        self._characteristic = characteristic

    @property
    def related_party(self) -> List[RelatedPartyRefOrPartyRoleRefFVO]:
        """Gets the related_party of this IntentFVO.


        :return: The related_party of this IntentFVO.
        :rtype: List[RelatedPartyRefOrPartyRoleRefFVO]
        """
        return self._related_party

    @related_party.setter
    def related_party(self, related_party: List[RelatedPartyRefOrPartyRoleRefFVO]):
        """Sets the related_party of this IntentFVO.


        :param related_party: The related_party of this IntentFVO.
        :type related_party: List[RelatedPartyRefOrPartyRoleRefFVO]
        """

        self._related_party = related_party

    @property
    def attachment(self) -> List[AttachmentRefOrValueFVO]:
        """Gets the attachment of this IntentFVO.

        Attachments that may be of relevance to this intent, such as picture, document, media  # noqa: E501

        :return: The attachment of this IntentFVO.
        :rtype: List[AttachmentRefOrValueFVO]
        """
        return self._attachment

    @attachment.setter
    def attachment(self, attachment: List[AttachmentRefOrValueFVO]):
        """Sets the attachment of this IntentFVO.

        Attachments that may be of relevance to this intent, such as picture, document, media  # noqa: E501

        :param attachment: The attachment of this IntentFVO.
        :type attachment: List[AttachmentRefOrValueFVO]
        """

        self._attachment = attachment

    @property
    def name(self) -> str:
        """Gets the name of this IntentFVO.

        The name of the intent.  # noqa: E501

        :return: The name of this IntentFVO.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this IntentFVO.

        The name of the intent.  # noqa: E501

        :param name: The name of this IntentFVO.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def expression(self) -> IntentExpression:
        """Gets the expression of this IntentFVO.


        :return: The expression of this IntentFVO.
        :rtype: IntentExpression
        """
        return self._expression

    @expression.setter
    def expression(self, expression: IntentExpression):
        """Sets the expression of this IntentFVO.


        :param expression: The expression of this IntentFVO.
        :type expression: IntentExpression
        """
        if expression is None:
            raise ValueError("Invalid value for `expression`, must not be `None`")  # noqa: E501

        self._expression = expression

    @property
    def creation_date(self) -> datetime:
        """Gets the creation_date of this IntentFVO.

        Date and time of the creation of this REST resource  # noqa: E501

        :return: The creation_date of this IntentFVO.
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date: datetime):
        """Sets the creation_date of this IntentFVO.

        Date and time of the creation of this REST resource  # noqa: E501

        :param creation_date: The creation_date of this IntentFVO.
        :type creation_date: datetime
        """

        self._creation_date = creation_date

    @property
    def last_update(self) -> datetime:
        """Gets the last_update of this IntentFVO.

        Date and time of the last update of this REST resource  # noqa: E501

        :return: The last_update of this IntentFVO.
        :rtype: datetime
        """
        return self._last_update

    @last_update.setter
    def last_update(self, last_update: datetime):
        """Sets the last_update of this IntentFVO.

        Date and time of the last update of this REST resource  # noqa: E501

        :param last_update: The last_update of this IntentFVO.
        :type last_update: datetime
        """

        self._last_update = last_update

    @property
    def lifecycle_status(self) -> str:
        """Gets the lifecycle_status of this IntentFVO.

        Used to indicate the current lifecycle status of this intent  # noqa: E501

        :return: The lifecycle_status of this IntentFVO.
        :rtype: str
        """
        return self._lifecycle_status

    @lifecycle_status.setter
    def lifecycle_status(self, lifecycle_status: str):
        """Sets the lifecycle_status of this IntentFVO.

        Used to indicate the current lifecycle status of this intent  # noqa: E501

        :param lifecycle_status: The lifecycle_status of this IntentFVO.
        :type lifecycle_status: str
        """

        self._lifecycle_status = lifecycle_status
