from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class JsonPatchFVO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, op=None, path=None, value=None, _from=None):  # noqa: E501
        """JsonPatchFVO - a model defined in OpenAPI

        :param op: The op of this JsonPatchFVO.  # noqa: E501
        :type op: str
        :param path: The path of this JsonPatchFVO.  # noqa: E501
        :type path: str
        :param value: The value of this JsonPatchFVO.  # noqa: E501
        :type value: object
        :param _from: The _from of this JsonPatchFVO.  # noqa: E501
        :type _from: str
        """
        self.openapi_types = {
            'op': str,
            'path': str,
            'value': object,
            '_from': str
        }

        self.attribute_map = {
            'op': 'op',
            'path': 'path',
            'value': 'value',
            '_from': 'from'
        }

        self._op = op
        self._path = path
        self._value = value
        self.__from = _from

    @classmethod
    def from_dict(cls, dikt) -> 'JsonPatchFVO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JsonPatch_FVO of this JsonPatchFVO.  # noqa: E501
        :rtype: JsonPatchFVO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def op(self) -> str:
        """Gets the op of this JsonPatchFVO.

        The operation to be performed  # noqa: E501

        :return: The op of this JsonPatchFVO.
        :rtype: str
        """
        return self._op

    @op.setter
    def op(self, op: str):
        """Sets the op of this JsonPatchFVO.

        The operation to be performed  # noqa: E501

        :param op: The op of this JsonPatchFVO.
        :type op: str
        """
        allowed_values = ["add", "remove", "replace", "move", "copy", "test"]  # noqa: E501
        if op not in allowed_values:
            raise ValueError(
                "Invalid value for `op` ({0}), must be one of {1}"
                .format(op, allowed_values)
            )

        self._op = op

    @property
    def path(self) -> str:
        """Gets the path of this JsonPatchFVO.

        A JSON-Pointer  # noqa: E501

        :return: The path of this JsonPatchFVO.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this JsonPatchFVO.

        A JSON-Pointer  # noqa: E501

        :param path: The path of this JsonPatchFVO.
        :type path: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def value(self) -> object:
        """Gets the value of this JsonPatchFVO.

        The value to be used within the operations.  # noqa: E501

        :return: The value of this JsonPatchFVO.
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value: object):
        """Sets the value of this JsonPatchFVO.

        The value to be used within the operations.  # noqa: E501

        :param value: The value of this JsonPatchFVO.
        :type value: object
        """

        self._value = value

    @property
    def _from(self) -> str:
        """Gets the _from of this JsonPatchFVO.

        A string containing a JSON Pointer value.  # noqa: E501

        :return: The _from of this JsonPatchFVO.
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from: str):
        """Sets the _from of this JsonPatchFVO.

        A string containing a JSON Pointer value.  # noqa: E501

        :param _from: The _from of this JsonPatchFVO.
        :type _from: str
        """

        self.__from = _from
