from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.time_period import TimePeriod
from openapi_server import util

from openapi_server.models.time_period import TimePeriod  # noqa: E501

class ServiceOrderRelationshipFVO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, base_type=None, schema_location=None, href=None, id=None, name=None, referred_type=None, valid_for=None, relationship_type=None):  # noqa: E501
        """ServiceOrderRelationshipFVO - a model defined in OpenAPI

        :param type: The type of this ServiceOrderRelationshipFVO.  # noqa: E501
        :type type: str
        :param base_type: The base_type of this ServiceOrderRelationshipFVO.  # noqa: E501
        :type base_type: str
        :param schema_location: The schema_location of this ServiceOrderRelationshipFVO.  # noqa: E501
        :type schema_location: str
        :param href: The href of this ServiceOrderRelationshipFVO.  # noqa: E501
        :type href: str
        :param id: The id of this ServiceOrderRelationshipFVO.  # noqa: E501
        :type id: str
        :param name: The name of this ServiceOrderRelationshipFVO.  # noqa: E501
        :type name: str
        :param referred_type: The referred_type of this ServiceOrderRelationshipFVO.  # noqa: E501
        :type referred_type: str
        :param valid_for: The valid_for of this ServiceOrderRelationshipFVO.  # noqa: E501
        :type valid_for: TimePeriod
        :param relationship_type: The relationship_type of this ServiceOrderRelationshipFVO.  # noqa: E501
        :type relationship_type: str
        """
        self.openapi_types = {
            'type': str,
            'base_type': str,
            'schema_location': str,
            'href': str,
            'id': str,
            'name': str,
            'referred_type': str,
            'valid_for': TimePeriod,
            'relationship_type': str
        }

        self.attribute_map = {
            'type': '@type',
            'base_type': '@baseType',
            'schema_location': '@schemaLocation',
            'href': 'href',
            'id': 'id',
            'name': 'name',
            'referred_type': '@referredType',
            'valid_for': 'validFor',
            'relationship_type': 'relationshipType'
        }

        self._type = type
        self._base_type = base_type
        self._schema_location = schema_location
        self._href = href
        self._id = id
        self._name = name
        self._referred_type = referred_type
        self._valid_for = valid_for
        self._relationship_type = relationship_type

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceOrderRelationshipFVO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceOrderRelationship_FVO of this ServiceOrderRelationshipFVO.  # noqa: E501
        :rtype: ServiceOrderRelationshipFVO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ServiceOrderRelationshipFVO.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :return: The type of this ServiceOrderRelationshipFVO.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ServiceOrderRelationshipFVO.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :param type: The type of this ServiceOrderRelationshipFVO.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def base_type(self) -> str:
        """Gets the base_type of this ServiceOrderRelationshipFVO.

        When sub-classing, this defines the super-class  # noqa: E501

        :return: The base_type of this ServiceOrderRelationshipFVO.
        :rtype: str
        """
        return self._base_type

    @base_type.setter
    def base_type(self, base_type: str):
        """Sets the base_type of this ServiceOrderRelationshipFVO.

        When sub-classing, this defines the super-class  # noqa: E501

        :param base_type: The base_type of this ServiceOrderRelationshipFVO.
        :type base_type: str
        """

        self._base_type = base_type

    @property
    def schema_location(self) -> str:
        """Gets the schema_location of this ServiceOrderRelationshipFVO.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :return: The schema_location of this ServiceOrderRelationshipFVO.
        :rtype: str
        """
        return self._schema_location

    @schema_location.setter
    def schema_location(self, schema_location: str):
        """Sets the schema_location of this ServiceOrderRelationshipFVO.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :param schema_location: The schema_location of this ServiceOrderRelationshipFVO.
        :type schema_location: str
        """

        self._schema_location = schema_location

    @property
    def href(self) -> str:
        """Gets the href of this ServiceOrderRelationshipFVO.

        The URI of the referred entity.  # noqa: E501

        :return: The href of this ServiceOrderRelationshipFVO.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this ServiceOrderRelationshipFVO.

        The URI of the referred entity.  # noqa: E501

        :param href: The href of this ServiceOrderRelationshipFVO.
        :type href: str
        """

        self._href = href

    @property
    def id(self) -> str:
        """Gets the id of this ServiceOrderRelationshipFVO.

        The id of the related order  # noqa: E501

        :return: The id of this ServiceOrderRelationshipFVO.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ServiceOrderRelationshipFVO.

        The id of the related order  # noqa: E501

        :param id: The id of this ServiceOrderRelationshipFVO.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this ServiceOrderRelationshipFVO.

        Name of the referred entity.  # noqa: E501

        :return: The name of this ServiceOrderRelationshipFVO.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ServiceOrderRelationshipFVO.

        Name of the referred entity.  # noqa: E501

        :param name: The name of this ServiceOrderRelationshipFVO.
        :type name: str
        """

        self._name = name

    @property
    def referred_type(self) -> str:
        """Gets the referred_type of this ServiceOrderRelationshipFVO.

        The actual type of the target instance when needed for disambiguation.  # noqa: E501

        :return: The referred_type of this ServiceOrderRelationshipFVO.
        :rtype: str
        """
        return self._referred_type

    @referred_type.setter
    def referred_type(self, referred_type: str):
        """Sets the referred_type of this ServiceOrderRelationshipFVO.

        The actual type of the target instance when needed for disambiguation.  # noqa: E501

        :param referred_type: The referred_type of this ServiceOrderRelationshipFVO.
        :type referred_type: str
        """

        self._referred_type = referred_type

    @property
    def valid_for(self) -> TimePeriod:
        """Gets the valid_for of this ServiceOrderRelationshipFVO.


        :return: The valid_for of this ServiceOrderRelationshipFVO.
        :rtype: TimePeriod
        """
        return self._valid_for

    @valid_for.setter
    def valid_for(self, valid_for: TimePeriod):
        """Sets the valid_for of this ServiceOrderRelationshipFVO.


        :param valid_for: The valid_for of this ServiceOrderRelationshipFVO.
        :type valid_for: TimePeriod
        """

        self._valid_for = valid_for

    @property
    def relationship_type(self) -> str:
        """Gets the relationship_type of this ServiceOrderRelationshipFVO.

        The type of related order, such as: [dependency] if the order needs to be [not started] until another order item is complete (a service order in this case) or [cross-ref] to keep track of the source order (a productOrder)  # noqa: E501

        :return: The relationship_type of this ServiceOrderRelationshipFVO.
        :rtype: str
        """
        return self._relationship_type

    @relationship_type.setter
    def relationship_type(self, relationship_type: str):
        """Sets the relationship_type of this ServiceOrderRelationshipFVO.

        The type of related order, such as: [dependency] if the order needs to be [not started] until another order item is complete (a service order in this case) or [cross-ref] to keep track of the source order (a productOrder)  # noqa: E501

        :param relationship_type: The relationship_type of this ServiceOrderRelationshipFVO.
        :type relationship_type: str
        """
        if relationship_type is None:
            raise ValueError("Invalid value for `relationship_type`, must not be `None`")  # noqa: E501

        self._relationship_type = relationship_type
