from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ServiceOrderStateType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ACKNOWLEDGED = 'acknowledged'
    REJECTED = 'rejected'
    PENDING = 'pending'
    HELD = 'held'
    INPROGRESS = 'inProgress'
    CANCELLED = 'cancelled'
    COMPLETED = 'completed'
    FAILED = 'failed'
    PARTIAL = 'partial'
    ASSESSINGCANCELLATION = 'assessingCancellation'
    PENDINGCANCELLATION = 'pendingCancellation'
    def __init__(self):  # noqa: E501
        """ServiceOrderStateType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceOrderStateType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceOrderStateType of this ServiceOrderStateType.  # noqa: E501
        :rtype: ServiceOrderStateType
        """
        return util.deserialize_model(dikt, cls)
