from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.milestone import Milestone
from openapi_server.models.service_order_item_ref import ServiceOrderItemRef
from openapi_server import util

from openapi_server.models.milestone import Milestone  # noqa: E501
from openapi_server.models.service_order_item_ref import ServiceOrderItemRef  # noqa: E501

class ServiceOrderMilestone(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, base_type=None, schema_location=None, description=None, id=None, status=None, milestone_date=None, name=None, message=None, service_order_item=None):  # noqa: E501
        """ServiceOrderMilestone - a model defined in OpenAPI

        :param type: The type of this ServiceOrderMilestone.  # noqa: E501
        :type type: str
        :param base_type: The base_type of this ServiceOrderMilestone.  # noqa: E501
        :type base_type: str
        :param schema_location: The schema_location of this ServiceOrderMilestone.  # noqa: E501
        :type schema_location: str
        :param description: The description of this ServiceOrderMilestone.  # noqa: E501
        :type description: str
        :param id: The id of this ServiceOrderMilestone.  # noqa: E501
        :type id: str
        :param status: The status of this ServiceOrderMilestone.  # noqa: E501
        :type status: str
        :param milestone_date: The milestone_date of this ServiceOrderMilestone.  # noqa: E501
        :type milestone_date: datetime
        :param name: The name of this ServiceOrderMilestone.  # noqa: E501
        :type name: str
        :param message: The message of this ServiceOrderMilestone.  # noqa: E501
        :type message: str
        :param service_order_item: The service_order_item of this ServiceOrderMilestone.  # noqa: E501
        :type service_order_item: List[ServiceOrderItemRef]
        """
        self.openapi_types = {
            'type': str,
            'base_type': str,
            'schema_location': str,
            'description': str,
            'id': str,
            'status': str,
            'milestone_date': datetime,
            'name': str,
            'message': str,
            'service_order_item': List[ServiceOrderItemRef]
        }

        self.attribute_map = {
            'type': '@type',
            'base_type': '@baseType',
            'schema_location': '@schemaLocation',
            'description': 'description',
            'id': 'id',
            'status': 'status',
            'milestone_date': 'milestoneDate',
            'name': 'name',
            'message': 'message',
            'service_order_item': 'serviceOrderItem'
        }

        self._type = type
        self._base_type = base_type
        self._schema_location = schema_location
        self._description = description
        self._id = id
        self._status = status
        self._milestone_date = milestone_date
        self._name = name
        self._message = message
        self._service_order_item = service_order_item

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceOrderMilestone':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceOrderMilestone of this ServiceOrderMilestone.  # noqa: E501
        :rtype: ServiceOrderMilestone
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ServiceOrderMilestone.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :return: The type of this ServiceOrderMilestone.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ServiceOrderMilestone.

        When sub-classing, this defines the sub-class Extensible name  # noqa: E501

        :param type: The type of this ServiceOrderMilestone.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def base_type(self) -> str:
        """Gets the base_type of this ServiceOrderMilestone.

        When sub-classing, this defines the super-class  # noqa: E501

        :return: The base_type of this ServiceOrderMilestone.
        :rtype: str
        """
        return self._base_type

    @base_type.setter
    def base_type(self, base_type: str):
        """Sets the base_type of this ServiceOrderMilestone.

        When sub-classing, this defines the super-class  # noqa: E501

        :param base_type: The base_type of this ServiceOrderMilestone.
        :type base_type: str
        """

        self._base_type = base_type

    @property
    def schema_location(self) -> str:
        """Gets the schema_location of this ServiceOrderMilestone.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :return: The schema_location of this ServiceOrderMilestone.
        :rtype: str
        """
        return self._schema_location

    @schema_location.setter
    def schema_location(self, schema_location: str):
        """Sets the schema_location of this ServiceOrderMilestone.

        A URI to a JSON-Schema file that defines additional attributes and relationships  # noqa: E501

        :param schema_location: The schema_location of this ServiceOrderMilestone.
        :type schema_location: str
        """

        self._schema_location = schema_location

    @property
    def description(self) -> str:
        """Gets the description of this ServiceOrderMilestone.

        free-text description of the Milestone  # noqa: E501

        :return: The description of this ServiceOrderMilestone.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ServiceOrderMilestone.

        free-text description of the Milestone  # noqa: E501

        :param description: The description of this ServiceOrderMilestone.
        :type description: str
        """

        self._description = description

    @property
    def id(self) -> str:
        """Gets the id of this ServiceOrderMilestone.

        identifier of the Milestone  # noqa: E501

        :return: The id of this ServiceOrderMilestone.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ServiceOrderMilestone.

        identifier of the Milestone  # noqa: E501

        :param id: The id of this ServiceOrderMilestone.
        :type id: str
        """

        self._id = id

    @property
    def status(self) -> str:
        """Gets the status of this ServiceOrderMilestone.

        The milestone status  # noqa: E501

        :return: The status of this ServiceOrderMilestone.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ServiceOrderMilestone.

        The milestone status  # noqa: E501

        :param status: The status of this ServiceOrderMilestone.
        :type status: str
        """
        allowed_values = ["Yet-To-Reach", "Completed", "Violated"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def milestone_date(self) -> datetime:
        """Gets the milestone_date of this ServiceOrderMilestone.

        A date time( DateTime). The date that the milestone happens  # noqa: E501

        :return: The milestone_date of this ServiceOrderMilestone.
        :rtype: datetime
        """
        return self._milestone_date

    @milestone_date.setter
    def milestone_date(self, milestone_date: datetime):
        """Sets the milestone_date of this ServiceOrderMilestone.

        A date time( DateTime). The date that the milestone happens  # noqa: E501

        :param milestone_date: The milestone_date of this ServiceOrderMilestone.
        :type milestone_date: datetime
        """

        self._milestone_date = milestone_date

    @property
    def name(self) -> str:
        """Gets the name of this ServiceOrderMilestone.

        A string used to give a name to the milestone  # noqa: E501

        :return: The name of this ServiceOrderMilestone.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ServiceOrderMilestone.

        A string used to give a name to the milestone  # noqa: E501

        :param name: The name of this ServiceOrderMilestone.
        :type name: str
        """

        self._name = name

    @property
    def message(self) -> str:
        """Gets the message of this ServiceOrderMilestone.

        A string represents the message of the milestone  # noqa: E501

        :return: The message of this ServiceOrderMilestone.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ServiceOrderMilestone.

        A string represents the message of the milestone  # noqa: E501

        :param message: The message of this ServiceOrderMilestone.
        :type message: str
        """

        self._message = message

    @property
    def service_order_item(self) -> List[ServiceOrderItemRef]:
        """Gets the service_order_item of this ServiceOrderMilestone.

        A list of order item references corresponded to this milestone  # noqa: E501

        :return: The service_order_item of this ServiceOrderMilestone.
        :rtype: List[ServiceOrderItemRef]
        """
        return self._service_order_item

    @service_order_item.setter
    def service_order_item(self, service_order_item: List[ServiceOrderItemRef]):
        """Sets the service_order_item of this ServiceOrderMilestone.

        A list of order item references corresponded to this milestone  # noqa: E501

        :param service_order_item: The service_order_item of this ServiceOrderMilestone.
        :type service_order_item: List[ServiceOrderItemRef]
        """

        self._service_order_item = service_order_item
